### ISSUE TITLE
Release Checklist: 1.1.0

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1147]
## New Release Details:

- Scope: Full Release
- Network: Karura
- Client Version: 1.1.0
- Runtime Version: 1001
- Release Branch: [release-karura-1.1.0](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.1.0)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.0.0...release-karura-1.1.0
- Substrate version: [9c572625f6557dfdb19f47474369a0327d51dfbc](https://github.com/paritytech/substrate/tree/9c572625f6557dfdb19f47474369a0327d51dfbc)
  - Diff: https://github.com/paritytech/substrate/compare/polkadot-v0.9.4...polkadot-v0.9.7
- ORML version: [9e5e78488496c221142678f60161659b1805d04d ](https://github.com/open-web3-stack/open-runtime-module-library/tree/9e5e78488496c221142678f60161659b1805d04d)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/3c64d532c8db5311b95d4f39d702d15bcd6319c1...9e5e78488496c221142678f60161659b1805d04d
- Cumulus version: [c5c3abf7eb9d4fdfb588d6560efaa8dca66a8dbc ](https://github.com/paritytech/cumulus/tree/c5c3abf7eb9d4fdfb588d6560efaa8dca66a8dbc)
  - Diff: https://github.com/paritytech/cumulus/compare/polkadot-v0.9.4...polkadot-v0.9.7
- Polkadot version: [5d35bac7408a4cb12a578764217d06f3920b36aa ](https://github.com/paritytech/polkadot/tree/5d35bac7408a4cb12a578764217d06f3920b36aa)
  - Diff: https://github.com/paritytech/polkadot/compare/release-v0.9.4...release-v0.9.7
- srtool details:

```
Summary:
  Generator  : srtool v0.9.12
  Version    : 1.1.0
  GIT commit : 72d7da3f8f362ffed8c81afcb301068664e09234
  GIT tag    : 1.0.0
  GIT branch : release-karura-1.1.0
  Rustc      : rustc 1.54.0-nightly (657bc0188 2021-05-31)
  Package    : karura-runtime
  Time       : 2021-07-01T02:57:39Z
=== Compact:
  Size       : 2739 KB (2804780 bytes)
  Proposal   : 0x63b6c37904ad8b0fd7df9b11706598fa3075b17f0fbf14ee848cb0362d28cf8c
  IPFS       : QmSUTSuEbbNYH8r6ionQKRibn5yrWyoUp9nTHc236qVYiM
  SHA256     : 0x44d8499c3313b931eb9b655c068863b7517a719bf2becde055a0624cab80ecd6
  Wasm       : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm
```

- subwasm info

```
 $ subwasm info karura_runtime.compact.compressed.wasm
🏋️  Runtime size:	2.675 MB (2,804,780 bytes)
🗜  Compressed:		Yes, 72.76%
✨ Reserved meta:	OK - [6D, 65, 74, 61]
🎁 Metadata version:	V13
🔥 Core version:	karura-1001 (karura-0.tx1.au1)
🗳️  Proposal hash:	0x63b6c37904ad8b0fd7df9b11706598fa3075b17f0fbf14ee848cb0362d28cf8c
#️⃣  Blake2-256 hash:	0x19af85651892f0d4d6cbedce5daaec0e40c809fb7aae6f1faaad05752db50050
📦 IPFS hash:		QmfKDGCgU73Lr7VpGqKnGEK8aGogbpSQZc4c4tpmuyUdhf (https://www.ipfs.io/ipfs/QmfKDGCgU73Lr7VpGqKnGEK8aGogbpSQZc4c4tpmuyUdhf)
```

## Client Release

- [x] Verify client `Cargo.toml` version has been incremented since the last release.
  - Current version: 1.1.0
  - Last version: 1.0.0
- [x] Check the new client have run on the network without issue for at lease 12 hours.
- [x] Check new docker image has been published.
  - [acala/karura-node:1.1.0](https://hub.docker.com/layers/acala/karura-node/1.1.0/images/sha256-8f75c2fd34254e235557ad05827c9e5e6db824046dfc5d38a16943575a8f079b)
- [ ] Check new client is able to sync from scratch

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 1001
  - Last version: 1000
- [x] Verify completed migrations are removed from any public networks.
- [ ] Review [subwasm diff](#subwasm-diff)
- [x] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [x] ORML
  - [x] Substrate
  - [x] Cumulus
  - [x] Acala
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [x] Verify benchmarks & weights have been updated for any modified runtime logics.
- [x] Verify we included all the necessary migrations.
  - [x] ORML
  - [x] Substrate
  - [x] Cumulus
  - [x] Acala
- [x] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [x] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [x] Ensure WASM is reproducible

## All Releases

- [x] Check new Github release is created with release logs.

## Post Release

- [x] Notify Discord announcement channel.
- [x] Ensure our own nodes are updated
- [x] Update [wiki](https://wiki.acala.network/karura/integration)

### SDK & Tools

- [x] acala.js
- [ ] txwrapper
- [ ] sidecar
- [x] acala-subql
- [x] oracle dispatcher

### dApps

- [x] polkadot apps
- [ ] Acala dApp

### Wallets

- [ ] Polkawallet
- [ ] Feareless

### Other

- [x] Exchanges
- [x] Gauntlet
- [x] Faucet (for Mandala)

# Notes

## subwasm diff

[subwasm](https://github.com/chevdor/subwasm/) can be used to verify wasm and check diff

```bash
$ subwasm diff karura_runtime.compact.compressed.wasm wss://karura-rpc-2.aca-api.network/ws
```

Review the output and make sure

**Comment by xlc** [comment]
Before upgrade:
- [ ] https://github.com/AcalaNetwork/Acala/issues/1135

**Comment by xlc** [comment]
```
$ subwasm info karura_runtime.compact.compressed.wasm
🏋️  Runtime size:	2.675 MB (2,804,780 bytes)
🗜  Compressed:		Yes, 72.76%
✨ Reserved meta:	OK - [6D, 65, 74, 61]
🎁 Metadata version:	V13
🔥 Core version:	karura-1001 (karura-0.tx1.au1)
🗳️  Proposal hash:	0x63b6c37904ad8b0fd7df9b11706598fa3075b17f0fbf14ee848cb0362d28cf8c
#️⃣  Blake2-256 hash:	0x19af85651892f0d4d6cbedce5daaec0e40c809fb7aae6f1faaad05752db50050
📦 IPFS hash:		QmSUTSuEbbNYH8r6ionQKRibn5yrWyoUp9nTHc236qVYiM (https://www.ipfs.io/ipfs/QmSUTSuEbbNYH8r6ionQKRibn5yrWyoUp9nTHc236qVYiM)
```
