### ISSUE TITLE
Release Checklist: 1.1.1

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1169]
## New Release Details:

- Scope: Runtime
- Network: Karura
- Client Version: 1.1.1
- Runtime Version: 1002
- Release Branch: [release-karura-1.1.1](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.1.1)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.1.0...release-karura-1.1.1
- Substrate version: [9c572625f6557dfdb19f47474369a0327d51dfbc](https://github.com/paritytech/substrate/tree/polkadot-v0.9.7)
  - Diff: Same as last release.
- ORML version: [443ee91bc2ca5f1fc155c0378eef6e89b67e2e97 ](https://github.com/open-web3-stack/open-runtime-module-library/tree/443ee91bc2ca5f1fc155c0378eef6e89b67e2e97)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/9e5e78488496c221142678f60161659b1805d04d...443ee91bc2ca5f1fc155c0378eef6e89b67e2e97
- Cumulus version: [c5c3abf7eb9d4fdfb588d6560efaa8dca66a8dbc ](https://github.com/paritytech/cumulus/tree/polkadot-v0.9.7)
  - Diff: Same as last release.
- Polkadot version: [5d35bac7408a4cb12a578764217d06f3920b36aa ](https://github.com/paritytech/polkadot/tree/release-v0.9.7)
  - Diff: Same as last release.
- srtool details:

```
Summary generated with srtool v0.9.15 using the docker image chevdor/srtool:1.53.0:
 Package     : karura-runtime v1.1.1
 GIT commit  : 02fd208a79b7b35624d8453a9aac3b7bb9f92524
 GIT tag     : 1.1.0
 GIT branch  : release-karura-1.1.1
 Rustc       : rustc 1.53.0 (53cb7b09b 2021-06-17)
 Time        : 2021-07-06T00:06:17Z

== Compact
 Version     : karura-1002 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 2.72 MB (2853554 bytes)
 Proposal    : 0xd1f26ef0e218a5e7bd017fe13990909a28fba5e47f7ffb06f5a4410569162f05
 IPFS        : QmVjMZUZ76AbFG9iT6sCGUd6jrgsFQEhMPUWipZgTRgzvw
 BLAKE2_256  : 0xd20ef58369c02e6c2cb49797c7298656d7cb433df766ddececa40f5e4b27211f
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-1002 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 758.75 KB (776963 bytes)
 Compression : 72.78%
 Proposal    : 0xd1f26ef0e218a5e7bd017fe13990909a28fba5e47f7ffb06f5a4410569162f05
 IPFS        : QmNpJ6jFp4cKZsSEWRf1Svx7fWpSqEYGDzJS6hmiejudqk
 BLAKE2_256  : 0xd20ef58369c02e6c2cb49797c7298656d7cb433df766ddececa40f5e4b27211f
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
subwasm info runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
🏋️  Runtime size:        2.721 MB (2,853,554 bytes)
🗜  Compressed:          Yes, 72.77%
✨ Reserved meta:       OK - [6D, 65, 74, 61]
🎁 Metadata version:    V13
🔥 Core version:        karura-1002 (karura-0.tx1.au1)
🗳️  Proposal hash:       0xd1f26ef0e218a5e7bd017fe13990909a28fba5e47f7ffb06f5a4410569162f05
#️⃣  Blake2-256 hash:     0xd20ef58369c02e6c2cb49797c7298656d7cb433df766ddececa40f5e4b27211f
📦 IPFS hash:           QmNpJ6jFp4cKZsSEWRf1Svx7fWpSqEYGDzJS6hmiejudqk (https://www.ipfs.io/ipfs/QmNpJ6jFp4cKZsSEWRf1Svx7fWpSqEYGDzJS6hmiejudqk)
```

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 1002
  - Last version: 1001
- [x] Verify completed migrations are removed from any public networks.
- [ ] Review subwasm diff
  - `subwasm diff karura_runtime.compact.compressed.wasm wss://karura-rpc-2.aca-api.network/ws`
- [ ] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Acala
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [x] Verify we included all the necessary migrations.
  - [x] ORML
  - [x] Substrate
  - [x] Cumulus
  - [x] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [ ] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated
- [ ] Update [wiki](https://wiki.acala.network/karura/integration)

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps

- [ ] polkadot apps
- [ ] Acala dApp

### Wallets

- [ ] Polkawallet
- [ ] Feareless

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)

**Comment by xlc** [comment]
- [ ] ensure collator pod account have ED
