### ISSUE TITLE
Release Checklist: 1.1.2

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1189]
## New Release Details:

- Scope: Runtime only
- Network: Karura
- Client Version: 1.1.2
- Runtime Version: 1003
- Release Branch: [release-karura-1.1.2](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.1.2)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.1.1...release-karura-1.1.2
- Substrate version: [9c572625f6557dfdb19f47474369a0327d51dfbc](https://github.com/paritytech/substrate/tree/polkadot-v0.9.7)
  - Diff: Same as last release.
- ORML version: [66939a4d111c2456afac1b48ac1e3441c0397377 ](https://github.com/open-web3-stack/open-runtime-module-library/tree/66939a4d111c2456afac1b48ac1e3441c0397377)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/9e5e78488496c221142678f60161659b1805d04d...66939a4d111c2456afac1b48ac1e3441c0397377
- Cumulus version: [c5c3abf7eb9d4fdfb588d6560efaa8dca66a8dbc ](https://github.com/paritytech/cumulus/tree/polkadot-v0.9.7)
  - Diff: Same as last release.
- Polkadot version: [5d35bac7408a4cb12a578764217d06f3920b36aa ](https://github.com/paritytech/polkadot/tree/release-v0.9.7)
  - Diff: Same as last release.
- srtool details:

```
Summary generated with srtool v0.9.15 using the docker image chevdor/srtool:1.53.0:
 Package     : karura-runtime v1.1.2
 GIT commit  : e444070fbabb7497d6af60de623f61cdf82aa22c
 GIT tag     : 1.1.1
 GIT branch  : release-karura-1.1.2
 Rustc       : rustc 1.53.0 (53cb7b09b 2021-06-17)
 Time        : 2021-07-11T01:41:08Z

== Compact
 Version     : karura-1003 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 2.75 MB (2887359 bytes)
 Proposal    : 0x1cf5457e2e68ccbeb860baccb20a70ccd69e3ce8548cd48a85a787e9e458ce5c
 IPFS        : Qmf1RpAs9pCEBaLsia63ayoBeS89A9R5ib68NXcnQFFiwv
 BLAKE2_256  : 0x984b35a5130f8afb90a42027334d837d99f6cf7ca4ac63b5e3d8137890bfd93a
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-1003 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 764.29 KB (782631 bytes)
 Compression : 72.9%
 Proposal    : 0x1cf5457e2e68ccbeb860baccb20a70ccd69e3ce8548cd48a85a787e9e458ce5c
 IPFS        : QmUwwBVPc6rp5xXee33FAUUU4t6Y3KMZRnHWLtaPqCstT3
 BLAKE2_256  : 0x984b35a5130f8afb90a42027334d837d99f6cf7ca4ac63b5e3d8137890bfd93a
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:	2.754 MB (2,887,359 bytes)
🗜  Compressed:		Yes, 72.89%
✨ Reserved meta:	OK - [6D, 65, 74, 61]
🎁 Metadata version:	V13
🔥 Core version:	karura-1003 (karura-0.tx1.au1)
🗳️  Proposal hash:	0x1cf5457e2e68ccbeb860baccb20a70ccd69e3ce8548cd48a85a787e9e458ce5c
#️⃣  Blake2-256 hash:	0x984b35a5130f8afb90a42027334d837d99f6cf7ca4ac63b5e3d8137890bfd93a
📦 IPFS hash:		QmUwwBVPc6rp5xXee33FAUUU4t6Y3KMZRnHWLtaPqCstT3 (https://www.ipfs.io/ipfs/QmUwwBVPc6rp5xXee33FAUUU4t6Y3KMZRnHWLtaPqCstT3)
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.1.1
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1169

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 1003
  - Last version: 1002
- [x] Verify completed migrations are removed from any public networks.
- [x] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws` karura_runtime.compact.compressed.wasm
- [x] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Acala
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [x] Verify benchmarks & weights have been updated for any modified runtime logics.
- [x] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [x] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [x] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated
- [x] Update [wiki](https://wiki.acala.network/karura/integration)

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps

- [ ] polkadot apps
- [ ] Acala dApp

### Wallets

- [ ] Polkawallet
- [ ] Feareless

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)

**Comment by xlc** [comment]
subwasm diff
```
Running subwasm v0.12.0
  🅰️  File("karura-1003.wasm")
  🅱️  Chain(OnchainBlock { endpoint: WebSocket("wss://karura-rpc-2.aca-api.network/ws"), block_ref: None })
  🅰️  2.754 MB (2,887,358 bytes)
  🅱️  2.721 MB (2,853,554 bytes)
Checking metadata versions:
  ✅ Both metadata versions are identical: V13
Checking core versions:
  ❌ The 2 core versions are different:
  🅰️  karura-1003 (karura-0.tx1.au1)
  🅱️  karura-1002 (karura-0.tx1.au1)
Checking runtime metadata:
  ❌  The metadata are different
Comparing V13 with V13
🛠  modules.0.constants.4.value.                       "186B6172757261186B617275726101000000EB0300000000000034DF6ACB689907609B0300000037E397FC7C91F5E40100000040FE3AD401F8959A05000000D2BC9897EED08F1502000000F78B278BE53F454C02000000DD718D5CC53262D401000000AB3C0572291FEB8B01000000BC9D89904F5B923F0100000037C8BB1350A9A2A8010000006EF953004BA30E5901000000F485C9145D3F0AAD01000000E3DF3F2AA8A5CC5701000000EA93E3F16F3D69620100000001000000" --> "186B6172757261186B617275726101000000EA0300000000000034DF6ACB689907609B0300000037E397FC7C91F5E40100000040FE3AD401F8959A05000000D2BC9897EED08F1502000000F78B278BE53F454C02000000DD718D5CC53262D401000000AB3C0572291FEB8B01000000BC9D89904F5B923F0100000037C8BB1350A9A2A8010000006EF953004BA30E5901000000F485C9145D3F0AAD01000000E3DF3F2AA8A5CC5701000000EA93E3F16F3D69620100000001000000"
🗑  modules.10.constants.5.                            {"documentation":[" The polynomial that is applied in order to derive fee from weight."],"name":"WeightToFee","ty":"Vec<WeightToFeeCoefficient<PalletBalanceOf<T>>>","value":"0408000000000000000000000000000000000000000001"}
🛠  modules.11.constants.1.value.                      "005039278C0400000000000000000000" --> "00204AA9D10100000000000000000000"
🛠  modules.17.constants.1.value.                                "04000000" --> "05000000"
🛠  modules.36.constants.0.value.                                "201C0000" --> "00E10000"
🛠  modules.36.constants.1.value.                                "40380000" --> "E0C40000"
🛠  modules.36.constants.2.value.                                "40380000" --> "E0C40000"
🛠  modules.43.calls.4.arguments.0.name.                            "owner" --> "currency_id_a"
🛠  modules.43.calls.4.arguments.0.ty.                       "T::AccountId" --> "CurrencyId"
🛠  modules.43.calls.4.arguments.1.name.                    "currency_id_a" --> "currency_id_b"
🗑  modules.43.calls.4.arguments.2.                    {"name":"currency_id_b","ty":"CurrencyId"}
Changes:
- unmodified	= 91.08% (143)
- added		=  0.00% (0)
- modified	=  7.01% (11)
- removed	=  1.91% (3)
Skipped:
- documentation	=     3
- bytes		=     0
```
