### ISSUE TITLE
Release Checklist: 1.1.3

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1201]
## New Release Details:

- Scope: Runtime only
- Network: Karura
- Client Version: 1.1.3
- Runtime Version: 1004
- Release Branch: [release-karura-1.1.3](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.1.3)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.1.2...release-karura-1.1.3
- Substrate version: [9c572625f6557dfdb19f47474369a0327d51dfbc](https://github.com/paritytech/substrate/tree/9c572625f6557dfdb19f47474369a0327d51dfbc)
  - Diff: Same as last release.
- ORML version: [66939a4d111c2456afac1b48ac1e3441c0397377 ](https://github.com/open-web3-stack/open-runtime-module-library/tree/66939a4d111c2456afac1b48ac1e3441c0397377)
  - Diff: Same as last release.
- Cumulus version: [c5c3abf7eb9d4fdfb588d6560efaa8dca66a8dbc](https://github.com/paritytech/cumulus/tree/c5c3abf7eb9d4fdfb588d6560efaa8dca66a8dbc)
  - Diff: Same as last release.
- Polkadot version: [5d35bac7408a4cb12a578764217d06f3920b36aa](https://github.com/paritytech/polkadot/tree/5d35bac7408a4cb12a578764217d06f3920b36aa)
  - Diff: Same as last release.
- srtool details:

```
Summary generated with srtool v0.9.15 using the docker image chevdor/srtool:1.53.0:
 Package     : karura-runtime v1.1.3
 GIT commit  : 5c06366dc6413089cacf10cdf9deb9a4601a88be
 GIT tag     : 1.1.2
 GIT branch  : release-karura-1.1.3
 Rustc       : rustc 1.53.0 (53cb7b09b 2021-06-17)
 Time        : 2021-07-14T03:55:52Z

== Compact
 Version     : karura-1004 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 2.77 MB (2900085 bytes)
 Proposal    : 0xa01b9773813e9bb558756ee66ad45abafa9e17951c2b6e1ba4a1a5d15738c0fb
 IPFS        : QmNyj8zkJoM1d2thDzAj8aWT9heDQmsdPiKe8HAAd5AvBX
 BLAKE2_256  : 0xca7544f3f9f2bfb4858bd8b5a323428a18e879fda9ceb209804228696e906f8b
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-1004 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 770.81 KB (789307 bytes)
 Compression : 72.79%
 Proposal    : 0xa01b9773813e9bb558756ee66ad45abafa9e17951c2b6e1ba4a1a5d15738c0fb
 IPFS        : QmTrUJragkgGrp3eNyun7n7p5zT8MFLE3s87o3ZJSyj4wf
 BLAKE2_256  : 0xca7544f3f9f2bfb4858bd8b5a323428a18e879fda9ceb209804228696e906f8b
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:	2.766 MB (2,900,085 bytes)
🗜  Compressed:		Yes, 72.78%
✨ Reserved meta:	OK - [6D, 65, 74, 61]
🎁 Metadata version:	V13
🔥 Core version:	karura-1004 (karura-0.tx1.au1)
🗳️  Proposal hash:	0xa01b9773813e9bb558756ee66ad45abafa9e17951c2b6e1ba4a1a5d15738c0fb
#️⃣  Blake2-256 hash:	0xca7544f3f9f2bfb4858bd8b5a323428a18e879fda9ceb209804228696e906f8b
📦 IPFS hash:		QmTrUJragkgGrp3eNyun7n7p5zT8MFLE3s87o3ZJSyj4wf (https://www.ipfs.io/ipfs/QmTrUJragkgGrp3eNyun7n7p5zT8MFLE3s87o3ZJSyj4wf)
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.1.2
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1189

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 1004
  - Last version: 1003
- [x] Verify completed migrations are removed from any public networks.
- [x] Review subwasm diff
  - `subwasm diff karura_runtime.compact.compressed.wasm wss://karura-rpc-2.aca-api.network/ws`
- [x] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Acala
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [x] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Acala
- [x] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [ ] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [x] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated
- [ ] Update [wiki](https://wiki.acala.network/karura/integration)

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)

**Comment by xlc** [comment]
```
$ subwasm diff wss://karura-rpc-2.aca-api.network/ws karura-1004.wasm
Running subwasm v0.12.0
  🅰️  Chain(OnchainBlock { endpoint: WebSocket("wss://karura-rpc-2.aca-api.network/ws"), block_ref: None })
  🅱️  File("karura-1004.wasm")
  🅰️  2.754 MB (2,887,359 bytes)
  🅱️  2.766 MB (2,900,085 bytes)
Checking metadata versions:
  ✅ Both metadata versions are identical: V13
Checking core versions:
  ❌ The 2 core versions are different:
  🅰️  karura-1003 (karura-0.tx1.au1)
  🅱️  karura-1004 (karura-0.tx1.au1)
Checking runtime metadata:
  ❌  The metadata are different
Comparing V13 with V13
🛠  modules.0.constants.4.value.                       "186B6172757261186B617275726101000000EB0300000000000034DF6ACB689907609B0300000037E397FC7C91F5E40100000040FE3AD401F8959A05000000D2BC9897EED08F1502000000F78B278BE53F454C02000000DD718D5CC53262D401000000AB3C0572291FEB8B01000000BC9D89904F5B923F0100000037C8BB1350A9A2A8010000006EF953004BA30E5901000000F485C9145D3F0AAD01000000E3DF3F2AA8A5CC5701000000EA93E3F16F3D69620100000001000000" --> "186B6172757261186B617275726101000000EC0300000000000034DF6ACB689907609B0300000037E397FC7C91F5E40100000040FE3AD401F8959A05000000D2BC9897EED08F1502000000F78B278BE53F454C02000000DD718D5CC53262D401000000AB3C0572291FEB8B01000000BC9D89904F5B923F0100000037C8BB1350A9A2A8010000006EF953004BA30E5901000000F485C9145D3F0AAD01000000E3DF3F2AA8A5CC5701000000EA93E3F16F3D69620100000001000000"
🛠  modules.8.event.0.arguments.0.                        "CurrencyIdOf<T>" --> "CurrencyId"
🛠  modules.8.event.0.arguments.1.                           "T::AccountId" --> "AccountId"
🛠  modules.8.event.0.arguments.2.                           "T::AccountId" --> "AccountId"
🛠  modules.8.event.0.arguments.3.                           "BalanceOf<T>" --> "Balance"
🛠  modules.8.event.1.arguments.0.                        "CurrencyIdOf<T>" --> "CurrencyId"
🛠  modules.8.event.1.arguments.1.                           "T::AccountId" --> "AccountId"
🛠  modules.8.event.2.arguments.0.                        "CurrencyIdOf<T>" --> "CurrencyId"
🛠  modules.8.event.2.arguments.1.                           "T::AccountId" --> "AccountId"
🛠  modules.8.event.2.arguments.2.                           "BalanceOf<T>" --> "Balance"
🛠  modules.8.event.3.arguments.0.                        "CurrencyIdOf<T>" --> "CurrencyId"
🛠  modules.8.event.3.arguments.1.                           "T::AccountId" --> "AccountId"
🛠  modules.8.event.3.arguments.2.                           "BalanceOf<T>" --> "Balance"
🛠  modules.17.event.0.arguments.0.                     "Vec<T::AccountId>" --> "Vec<AccountId>"
🛠  modules.43.event.0.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.43.event.1.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.43.event.2.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.43.event.3.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.44.event.2.arguments.3.                          "T::AccountId" --> "AccountId"
🛠  modules.45.event.0.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.45.event.1.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.45.event.2.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.45.event.2.arguments.1.                          "T::AccountId" --> "AccountId"
🛠  modules.46.event.0.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.46.event.0.arguments.1.                          "T::AccountId" --> "AccountId"
🛠  modules.46.event.1.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.46.event.1.arguments.1.                          "T::AccountId" --> "AccountId"
🛠  modules.46.event.2.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.48.event.0.arguments.1.                          "T::AccountId" --> "AccountId"
🛠  modules.48.event.1.arguments.1.                          "T::AccountId" --> "AccountId"
🛠  modules.48.event.2.arguments.1.                          "T::AccountId" --> "AccountId"
🛠  modules.48.event.3.arguments.1.                          "Option<Rate>" --> "OptionRate"
🛠  modules.48.event.4.arguments.1.                         "Option<Ratio>" --> "OptionRatio"
🛠  modules.48.event.5.arguments.1.                          "Option<Rate>" --> "OptionRate"
🛠  modules.48.event.6.arguments.1.                         "Option<Ratio>" --> "OptionRatio"
🛠  modules.49.event.0.arguments.0.                        "T::BlockNumber" --> "BlockNumber"
🛠  modules.49.event.1.arguments.0.                        "T::BlockNumber" --> "BlockNumber"
🛠  modules.49.event.2.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.50.event.0.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.50.event.1.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.50.event.2.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.50.event.2.arguments.1.                    "PoolId<T::RelaychainAccountId>" --> "PoolId"
🛠  modules.50.event.3.arguments.0.                    "PoolId<T::RelaychainAccountId>" --> "PoolId"
🛠  modules.50.event.4.arguments.0.                    "PoolId<T::RelaychainAccountId>" --> "PoolId"
🛠  modules.50.event.5.arguments.0.                    "PoolId<T::RelaychainAccountId>" --> "PoolId"
🛠  modules.51.event.0.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.51.event.0.arguments.1.                          "ClassIdOf<T>" --> "ClassId"
🛠  modules.51.event.1.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.51.event.1.arguments.1.                          "T::AccountId" --> "AccountId"
🛠  modules.51.event.1.arguments.2.                          "ClassIdOf<T>" --> "ClassId"
🛠  modules.51.event.2.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.51.event.2.arguments.1.                          "T::AccountId" --> "AccountId"
🛠  modules.51.event.2.arguments.2.                          "ClassIdOf<T>" --> "ClassId"
🛠  modules.51.event.2.arguments.3.                          "TokenIdOf<T>" --> "TokenId"
🛠  modules.51.event.3.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.51.event.3.arguments.1.                          "ClassIdOf<T>" --> "ClassId"
🛠  modules.51.event.3.arguments.2.                          "TokenIdOf<T>" --> "TokenId"
🛠  modules.51.event.4.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.51.event.4.arguments.1.                          "ClassIdOf<T>" --> "ClassId"
🛠  modules.51.event.4.arguments.2.                          "TokenIdOf<T>" --> "TokenId"
🛠  modules.51.event.4.arguments.3.                               "T::Hash" --> "Hash"
🛠  modules.51.event.5.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.51.event.5.arguments.1.                          "ClassIdOf<T>" --> "ClassId"
🛠  modules.52.event.5.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.52.event.6.arguments.0.                          "T::AccountId" --> "AccountId"
🛠  modules.52.event.13.arguments.0.                         "T::AccountId" --> "AccountId"
🛠  modules.52.event.14.arguments.0.                         "T::AccountId" --> "AccountId"
🛠  modules.54.event.0.arguments.0.                          "T::AccountId" --> "AccountId"
Changes:
- unmodified	= 79.90% (322)
- added		=  0.25% (1)
- modified	= 19.85% (80)
- removed	=  0.00% (0)
Skipped:
- documentation	=    12
- bytes		=     0
```
