### ISSUE TITLE
Release Checklist: 1.2.0

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1213]
## New Release Details:

- Scope: Client Only
- Network: Karura
- Client Version: 1.2.0
- Runtime Version: 1004
- Release Branch: [release-karura-1.2.0](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.2.0)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.1.3...release-karura-1.2.0
- Substrate version: [polkadot-v0.9.8](https://github.com/paritytech/substrate/tree/1b758b2a8d151d97d2242260c465b6df9cb8a7a4)
  - Diff: https://github.com/paritytech/substrate/compare/polkadot-v0.9.7...polkadot-v0.9.8
- ORML version: [ca054d3078a8d157d0c176ed319d6ff49f38d349](https://github.com/open-web3-stack/open-runtime-module-library/tree/ca054d3078a8d157d0c176ed319d6ff49f38d349)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/66939a4d111c2456afac1b48ac1e3441c0397377... ca054d3078a8d157d0c176ed319d6ff49f38d349
- Cumulus version: [polkadot-v0.9.8](https://github.com/paritytech/cumulus/tree/4e51d32fdc4636f2d207204a25534e01d5fddf75)
  - Diff: https://github.com/paritytech/cumulus/compare/polkadot-v0.9.7...polkadot-v0.9.8
- Polkadot version: [release-v0.9.8](https://github.com/paritytech/polkadot/tree/3a10ee63c0b5703a1c802db3438ab7e01344a8ce)
  - Diff: https://github.com/paritytech/polkadot/compare/release-v0.9.7...release-v0.9.8

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.1.3
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1201

## Client Release

- [x] Verify client `Cargo.toml` version has been incremented since the last release.
  - Current version: 1.2.0
  - Last version: 1.1.3
- [ ] Check the new client have run on the network without issue for at lease 12 hours.
- [x] Check new docker image has been published.
  - [acala/karura-node:1.2.0](https://hub.docker.com/layers/acala/karura-node/1.2.0/images/sha256-9c2d8ae1da1a57c0ef4fbaf48a8178b37270b3eb4fc7c2eda983e68cb1de7014)
- [x] Check new client is able to sync from scratch
  -  `docker run --rm acala/karura-node:1.2.0 --chain=karura -- --chain=dev`

## All Releases

- [x] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated
- [ ] Update [wiki](https://wiki.acala.network/karura/integration)

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)

**Comment by xlc** [comment]
Got syncing issues and waiting for upstream fix. Will need to make new release after the upstream issues are fixed.
