### ISSUE TITLE
Next runtime upgrade checklist

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1237]
Pre upgrade:
- [ ] make sure we don't have any NFT storages: https://github.com/open-web3-stack/open-runtime-module-library/pull/562
- [x] make sure we don't have runtime level upgrades: https://github.com/paritytech/substrate/pull/9399
- [x] Transfer KSM to KaruraTreasuryAccount for ED. https://karura.subscan.io/account/5EYCAe5fiQJsoL71D8qNrZ7NznTuLKXk24Wjp9pe18su2Yk1
- [ ] make sure acala.js is upgraded https://github.com/AcalaNetwork/Acala/pull/1252#discussion_r676257352 @qwer951123 

Post upgrade:
- [ ] remove the upgrade: https://github.com/AcalaNetwork/Acala/blob/8c69db09747622d20abae1937adef234755c7cea/modules/session-manager/src/lib.rs#L154-L156
- [ ] Treasury can take xcm execution revenue after this release. For post runtime upgrade, we need to mint the equal amount of KSM to execution fees burned.
- [ ] Cleanup vesting storage https://github.com/open-web3-stack/open-runtime-module-library/pull/560
