### ISSUE TITLE
Release Checklist: 1.2.1

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1247]
## New Release Details:

- Scope: Client Only
- Network: Karura
- Client Version: 1.2.1
- Runtime Version: 1005
- Release Branch: [release-karura-1.2.1](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.2.1)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.2.0...release-karura-1.2.1
- Substrate version: [74101dc21cfffb4c2d014fcc28edc166d5ca1b16](https://github.com/paritytech/substrate/tree/74101dc21cfffb4c2d014fcc28edc166d5ca1b16)
  - Diff: https://github.com/paritytech/substrate/compare/1b758b2a8d151d97d2242260c465b6df9cb8a7a4...74101dc21cfffb4c2d014fcc28edc166d5ca1b16
- ORML version: [fa64469d84133f7285cea3a5ed1c201926bc364e](https://github.com/open-web3-stack/open-runtime-module-library/tree/fa64469d84133f7285cea3a5ed1c201926bc364e)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/ca054d3078a8d157d0c176ed319d6ff49f38d349...fa64469d84133f7285cea3a5ed1c201926bc364e
- Cumulus version: [ed6ba5dfb2c112c29505e856e8971da3420ce6d0](https://github.com/paritytech/cumulus/tree/ed6ba5dfb2c112c29505e856e8971da3420ce6d0)
  - Diff: https://github.com/paritytech/cumulus/compare/4e51d32fdc4636f2d207204a25534e01d5fddf75...ed6ba5dfb2c112c29505e856e8971da3420ce6d0
- Polkadot version: [3a10ee63c0b5703a1c802db3438ab7e01344a8ce](https://github.com/paritytech/polkadot/tree/3a10ee63c0b5703a1c802db3438ab7e01344a8ce)
  - Diff: https://github.com/paritytech/polkadot/compare/3a10ee63c0b5703a1c802db3438ab7e01344a8ce...3a10ee63c0b5703a1c802db3438ab7e01344a8ce

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.2.0
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1213

## Client Release

- [x] Verify client `Cargo.toml` version has been incremented since the last release.
  - Current version: 1.2.1
  - Last version: 1.2.0
- [x] Check the new client have run on the network without issue for at lease 12 hours.
- [x] Check new docker image has been published.
  - [acala/karura-node:1.2.1](https://hub.docker.com/layers/acala/karura-node/1.2.1/images/sha256-4f314b32b630fe2fb9864af7f4a16cd1f259ffdd884b60aa1d9f84807cd6f9f1?context=explore)
- [x] Check new client is able to sync from scratch
  -  `docker run --rm acala/karura-node:latest --chain=karura -- --chain=dev`

## All Releases

- [x] Check new Github release is created with release logs.

## Post Release

- [x] Notify Discord announcement channel.
- [x] Ensure our own nodes are updated

**Comment by zjb0807** [comment]
Transfer KSM to KaruraTreasuryAccount for ED. 

https://karura.subscan.io/account/5EYCAe5fiQJsoL71D8qNrZ7NznTuLKXk24Wjp9pe18su2Yk1

**Comment by shaunxw** [comment]
Treasury can take xcm execution revenue after this release. For post release, we need to mint the equal amount of KSM to execution fees burned.

**Comment by zjb0807** [comment]
> Transfer KSM to KaruraTreasuryAccount for ED.
> 
> https://karura.subscan.io/account/5EYCAe5fiQJsoL71D8qNrZ7NznTuLKXk24Wjp9pe18su2Yk1

The PR will fix it. Treasury only needs KAR for ED.
https://github.com/open-web3-stack/open-runtime-module-library/pull/567

**Comment by xlc** [comment]
This is a client only release. Will make a runtime release next Monday.
