### ISSUE TITLE
Release Checklist: 1.2.3

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1300]
## New Release Details:

- Scope: Runtime Only
- Network: Karura
- Client Version: 1.2.3
- Runtime Version: 1006
- Release Branch: [release-karura-1.2.3](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.2.3)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.2.2...release-karura-1.2.3
- Substrate version: [polkadot-v0.9.8](https://github.com/paritytech/substrate/tree/74101dc21cfffb4c2d014fcc28edc166d5ca1b16)
  - Diff: Same as last release
- ORML version: [8895f4b4c6ce9b9f03652bfe9602f102c7caa937](https://github.com/open-web3-stack/open-runtime-module-library/tree/8895f4b4c6ce9b9f03652bfe9602f102c7caa937)
  - Diff: Same as last release
- Cumulus version: [polkadot-v0.9.8](https://github.com/paritytech/cumulus/tree/ed6ba5dfb2c112c29505e856e8971da3420ce6d0)
  - Diff: Same as last release
- Polkadot version: [release-v0.9.8](https://github.com/paritytech/polkadot/tree/3a10ee63c0b5703a1c802db3438ab7e01344a8ce)
  - Diff: Same as last release
- srtool details:

```
Summary generated with srtool v0.9.16 using the docker image paritytech/srtool:1.53.0:
 Package     : karura-runtime v1.2.3
 GIT commit  : a1d4800e4e207a962f5082722dd72ba90abcebb1
 GIT tag     : 1.2.2
 GIT branch  : release-karura-1.2.3
 Rustc       : rustc 1.53.0 (53cb7b09b 2021-06-17)
 Time        : 2021-08-06T07:14:29Z

== Compact
 Version     : karura-1006 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 2.79 MB (2924451 bytes)
 Proposal    : 0xfb241c8c9494241fe72130109281ef22a8e9bcd25cb0825de718738c45c2a072
 IPFS        : Qmedb1RcdkEyootjta9mU1L29LDjTjav1TbusHxqEPncS1
 BLAKE2_256  : 0xad48881373a420f8a2aa1bea0869177ad1ad1c99d7bd89d23690bc0272f2b255
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-1006 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 783.13 KB (801924 bytes)
 Compression : 72.58%
 Proposal    : 0xc83977d0010419f1c8fdb39a249d368021c8f8dadb1d3f9deddaef7436386d85
 IPFS        : QmerV2sM9kDbHaZjj96rNtZwobwBcC5ei9cNKAPtsPvUKq
 BLAKE2_256  : 0x2b021b633da9960ddf22519c5769f1e094a1a617dff0f86133da5e48b47b67e4
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:		0.765 MB (801,924 bytes)
🗜  Compressed:			Yes, 72.58%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V13
🔥 Core version:		karura-1006 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0xc83977d0010419f1c8fdb39a249d368021c8f8dadb1d3f9deddaef7436386d85
🗳️  authorizeUpgrade hash:	0x84d8885b074e5d5d9718951caa1d9bea72431da7453f1a2ed82e1b338262c6ed
#️⃣  Blake2-256 hash:		0x2b021b633da9960ddf22519c5769f1e094a1a617dff0f86133da5e48b47b67e4
📦 IPFS hash:			QmerV2sM9kDbHaZjj96rNtZwobwBcC5ei9cNKAPtsPvUKq (https://www.ipfs.io/ipfs/QmerV2sM9kDbHaZjj96rNtZwobwBcC5ei9cNKAPtsPvUKq)
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.2.2
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1256

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 1006
  - Last version: 1005
- [x] Verify completed migrations are removed from any public networks.
- [ ] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [x] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [x] Verify benchmarks & weights have been updated for any modified runtime logics.
- [x] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [x] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [ ] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)

**Comment by xlc** [comment]
```
$ subwasm diff wss://karura-rpc-2.aca-api.network/ws karura-1006.wasm
Running subwasm v0.13.2
  🅰️  Chain(OnchainBlock { endpoint: WebSocket("wss://karura-rpc-2.aca-api.network/ws"), block_ref: None })
  🅱️  File("karura-1006.wasm")
  🅰️  0.767 MB (803,899 bytes)
  🅱️  0.765 MB (801,924 bytes)
Checking metadata versions:
  ✅ Both metadata versions are identical: V13
Checking core versions:
  ❌ The 2 core versions are different:
  🅰️  karura-1005 (karura-0.tx1.au1)
  🅱️  karura-1006 (karura-0.tx1.au1)
Checking runtime metadata:
  ❌  The metadata are different
Comparing V13 with V13
🛠  modules.0.constants.4.value.                       "186B6172757261186B617275726101000000ED0300000000000034DF6ACB689907609B0300000037E397FC7C91F5E40100000040FE3AD401F8959A05000000D2BC9897EED08F1503000000F78B278BE53F454C02000000DD718D5CC53262D401000000AB3C0572291FEB8B01000000BC9D89904F5B923F0100000037C8BB1350A9A2A8010000006EF953004BA30E5901000000F485C9145D3F0AAD01000000E3DF3F2AA8A5CC5701000000EA93E3F16F3D69620100000001000000" --> "186B6172757261186B617275726101000000EE0300000000000034DF6ACB689907609B0300000037E397FC7C91F5E40100000040FE3AD401F8959A05000000D2BC9897EED08F1503000000F78B278BE53F454C02000000DD718D5CC53262D401000000AB3C0572291FEB8B01000000BC9D89904F5B923F0100000037C8BB1350A9A2A8010000006EF953004BA30E5901000000F485C9145D3F0AAD01000000E3DF3F2AA8A5CC5701000000EA93E3F16F3D69620100000001000000"
🛠  modules.4.constants.0.value.                       "0078CFB5D30100000000000000000000" --> "0028DACED70100000000000000000000"
🛠  modules.4.constants.1.value.                       "0020BCBE000000000000000000000000" --> "0060343C020000000000000000000000"
🛠  modules.5.constants.0.value.                       "0028F9D8D10100000000000000000000" --> "00385738D20100000000000000000000"
🛠  modules.5.constants.1.value.                       "0001B2C4000000000000000000000000" --> "0003164E020000000000000000000000"
🛠  modules.5.constants.4.value.                       "0028F9D8D10100000000000000000000" --> "00385738D20100000000000000000000"
🛠  modules.5.constants.5.value.                       "00026489010000000000000000000000" --> "00062C9C040000000000000000000000"
🛠  modules.10.storage.entries.1.name.                 "DefaultFeeCurrencyId" --> "AlternativeFeeSwapPath"
🛠  modules.10.storage.entries.1.ty.Map.value.                 "CurrencyId" --> "BoundedVec<CurrencyId, T::TradingPathLimit>"
🗑  modules.10.storage.entries.2.                      {"default":"00","documentation":[" The alternative fee swap path of accounts."],"modifier":"Optional","name":"AlternativeFeeSwapPath","ty":{"Map":{"hasher":"Twox64Concat","key":"T::AccountId","unused":false,"value":"BoundedVec<CurrencyId, T::TradingPathLimit>"}}}
🛠  modules.12.constants.0.value.                      "00E1F505000000000000000000000000" --> "00A3E111000000000000000000000000"
🛠  modules.13.constants.3.value.                      "00E1F505000000000000000000000000" --> "00A3E111000000000000000000000000"
🛠  modules.38.constants.0.value.                                "201C0000" --> "302A0000"
🛠  modules.38.constants.6.value.                      "00E1F505000000000000000000000000" --> "00A3E111000000000000000000000000"
🛠  modules.48.constants.0.value.                      "0060C226D30100000000000000000000" --> "00E0B221D60100000000000000000000"
🛠  modules.50.event.3.name.                           "InterestRatePerSec" --> "InterestRatePerSecUpdated"
🛠  modules.53.constants.2.value.                      "00E1F505000000000000000000000000" --> "00A3E111000000000000000000000000"
🛠  modules.54.constants.1.value.                      "00E1F505000000000000000000000000" --> "00A3E111000000000000000000000000"
Changes:
- unmodified	= 90.48% (209)
- added		=  0.00% (0)
- modified	=  7.79% (18)
- removed	=  1.73% (4)
Skipped:
- documentation	=     4
- bytes		=     0
```
