### ISSUE TITLE
Release Checklist: 1.3.1

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1356]
## New Release Details:

- Scope: Runtime Only
- Network: Karura
- Client Version: 1.3.1
- Runtime Version: 1008
- Release Branch: [release-karura-1.3.1](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.3.1)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.3.0...release-karura-1.3.1
- Substrate version: [XXX](https://github.com/paritytech/substrate/tree/XXX)
  - Diff: https://github.com/paritytech/substrate/compare/polkadot-vXXX...polkadot-vXXX
- ORML version: [XXX](https://github.com/open-web3-stack/open-runtime-module-library/tree/XXX)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/XXX...XXX
- Cumulus version: [XXX](https://github.com/paritytech/cumulus/tree/XXX)
  - Diff: https://github.com/paritytech/cumulus/compare/polkadot-vXXX...polkadot-vXXX
- Polkadot version: [XXX](https://github.com/paritytech/polkadot/tree/XXX)
  - Diff: https://github.com/paritytech/polkadot/compare/release-vXXX...release-vXXX
- srtool details:

```
XXX
```

- subwasm info

```
XXX
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.3.0
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1326

## Runtime Release

- [ ] Verify `spec_version` has been incremented since the last release.
  - Current version: XXX
  - Last version: XXX
- [ ] Verify completed migrations are removed from any public networks.
- [ ] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [ ] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [ ] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [ ] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)
