### ISSUE TITLE
Release Checklist: 1.4.2

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1416]
## New Release Details:

- Scope: Runtime Only
- Network: Karura
- Client Version: 1.4.2
- Runtime Version: 1010
- Release Branch: [release-karura-1.4.2](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.4.2)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.4.1...release-karura-1.4.2
- Substrate version: [polkadot-v0.9.9](https://github.com/paritytech/substrate/tree/91061a7d925b5bc597804293da283477512ba4ff)
  - Diff: Same as last release
- ORML version: [fc4496e48405887ce901ab581d0139d7449aa771](https://github.com/open-web3-stack/open-runtime-module-library/tree/fc4496e48405887ce901ab581d0139d7449aa771)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/59df1dfc1a04d781906ee4442bbd410c9ca3ce68...fc4496e48405887ce901ab581d0139d7449aa771
- Cumulus version: [polkadot-v0.9.9](https://github.com/paritytech/cumulus/tree/fd80849dde5c209c20a996cfcc5aaacd4666dcbe)
  - Diff: Same as last release
- Polkadot version: [release-v0.9.9](https://github.com/paritytech/polkadot/tree/7a9f624777ad2d2adb3a1e6797a31f9d653c9587)
  - Diff: Same as last release
- srtool details:

```
Summary generated with srtool v0.9.16 using the docker image paritytech/srtool:1.53.0:
 Package     : karura-runtime v1.4.2
 GIT commit  : e0aa063e4f9e21efb42fd872edd9e4d2bd26dcdd
 GIT tag     : 1.4.1
 GIT branch  : release-karura-1.4.2
 Rustc       : rustc 1.53.0 (53cb7b09b 2021-06-17)
 Time        : 2021-09-16T03:10:34Z

== Compact
 Version     : karura-1010 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 2.90 MB (3043524 bytes)
 Proposal    : 0x42b943c36857432525b4710f563ecbb02c6c7c82af8c420b422e0d920bb49401
 IPFS        : QmbXStNRKDetTweV92VPGGbKLGV9MgJ3bmhUruoTTckpKG
 BLAKE2_256  : 0x7dfaf83936c87cb8ba6149ddff7981d41a2be1575a975556b552e88f275b1f14
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-1010 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 809.61 KB (829044 bytes)
 Compression : 72.77%
 Proposal    : 0x4e06931820259572eb71c58fb2780275720883169a528f1d0a0bb43abfd1dfcb
 IPFS        : Qmci4zJ8iCd82ZWLKb4QgRWzsHaA492EKjsZC41HGH8L7E
 BLAKE2_256  : 0x16a91c693eca3683b483451d26e79f73c37f998b93530b9ab4fa89662f06580e
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:		0.791 MB (829,044 bytes)
🗜  Compressed:			Yes, 72.76%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V13
🔥 Core version:		karura-1010 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0x4e06931820259572eb71c58fb2780275720883169a528f1d0a0bb43abfd1dfcb
🗳️  authorizeUpgrade hash:	0xf93354d95c7d3158db10b2bed756ef1b3364a76d8da232629cd8691fde3a6760
#️⃣  Blake2-256 hash:		0x16a91c693eca3683b483451d26e79f73c37f998b93530b9ab4fa89662f06580e
📦 IPFS:			https://www.ipfs.io/ipfs/Qmci4zJ8iCd82ZWLKb4QgRWzsHaA492EKjsZC41HGH8L7E
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.4.1
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1398

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 1010
  - Last version: 1009
- [x] Verify completed migrations are removed from any public networks.
- [ ] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [x] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [x] Verify benchmarks & weights have been updated for any modified runtime logics.
- [ ] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [x] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [x] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [x] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)

**Comment by xlc** [comment]
Need some manual testing for
- [ ] https://github.com/open-web3-stack/open-runtime-module-library/pull/604
- [ ] https://github.com/open-web3-stack/open-runtime-module-library/pull/603

**Comment by xlc** [comment]
```
Running subwasm v0.14.0
  🅰️  Chain(OnchainBlock { endpoint: WebSocket("wss://karura-rpc-2.aca-api.network/ws"), block_ref: None })
  🅱️  File("karura-1010.wasm")
  🅰️  0.773 MB (810,144 bytes)
  🅱️  0.791 MB (829,044 bytes)
Checking metadata versions:
  ✅ Both metadata versions are identical: V13
Checking core versions:
  ❌ The 2 core versions are different:
  🅰️  karura-1009 (karura-0.tx1.au1)
  🅱️  karura-1010 (karura-0.tx1.au1)
Checking runtime metadata:
  ❌  The metadata are different
Comparing V13 with V13
🛠  modules.0.constants.4.value.                       "186B6172757261186B617275726101000000F10300000000000034DF6ACB689907609B0300000037E397FC7C91F5E40100000040FE3AD401F8959A05000000D2BC9897EED08F1503000000F78B278BE53F454C02000000DD718D5CC53262D401000000AB3C0572291FEB8B01000000BC9D89904F5B923F0100000037C8BB1350A9A2A8010000006EF953004BA30E5901000000F485C9145D3F0AAD01000000E3DF3F2AA8A5CC5701000000EA93E3F16F3D69620100000001000000" --> "186B6172757261186B617275726101000000F20300000000000034DF6ACB689907609B0300000037E397FC7C91F5E40100000040FE3AD401F8959A05000000D2BC9897EED08F1503000000F78B278BE53F454C02000000DD718D5CC53262D401000000AB3C0572291FEB8B01000000BC9D89904F5B923F0100000037C8BB1350A9A2A8010000006EF953004BA30E5901000000F485C9145D3F0AAD01000000E3DF3F2AA8A5CC5701000000EA93E3F16F3D69620100000001000000"
🛠  modules.43.errors.                                                   "" --> [{"documentation":[" Pool does not exist"],"name":"PoolDoesNotExist"}]
🛠  modules.43.storage.entries.0.ty.Map.key.                    "T::PoolId" --> "T::PoolIdV0"
🛠  modules.43.storage.entries.0.ty.Map.value.         "PoolInfo<T::Share, T::Balance>" --> "PoolInfoV0<T::Share, T::Balance>"
🛠  modules.43.storage.entries.1.default.              "0000000000000000000000000000000000000000000000000000000000000000" --> "0000000000000000000000000000000000"
🛠  modules.43.storage.entries.1.name.                 "ShareAndWithdrawnReward" --> "PoolInfos"
🗑  modules.43.storage.entries.1.ty.DoubleMap.         {"hasher":"Twox64Concat","key1":"T::PoolId","key2":"T::AccountId","key2_hasher":"Twox64Concat","value":"(T::Share, T::Balance)"}
🛠  modules.54.calls.2.arguments.0.ty.                 "PoolId<T::RelaychainAccountId>" --> "PoolId"
🛠  modules.54.calls.3.arguments.0.ty.                 "Vec<(PoolId<T::RelaychainAccountId>, Balance)>" --> "Vec<(PoolId, Vec<(CurrencyId, Balance)>)>"
🛠  modules.54.calls.4.arguments.0.ty.                 "Vec<(PoolId<T::RelaychainAccountId>, Rate)>" --> "Vec<(PoolId, Rate)>"
🛠  modules.54.calls.5.arguments.0.ty.                 "Vec<(PoolId<T::RelaychainAccountId>, Rate)>" --> "Vec<(PoolId, Rate)>"
🛠  modules.54.calls.5.name.                           "update_payout_deduction_rates" --> "update_claim_reward_deduction_rates"
🛠  modules.54.calls.6.arguments.0.name.                          "pool_id" --> "count"
🛠  modules.54.calls.6.arguments.0.ty.                 "PoolId<T::RelaychainAccountId>" --> "u32"
🗑  modules.54.calls.6.arguments.1.                    {"name":"amount","ty":"Balance"}
🛠  modules.54.calls.6.name.                                "add_allowance" --> "migrate_share_and_withdrawn_reward"
🛠  modules.54.constants.4.name.                       "NativeRewardsSource" --> "RewardsSource"
🛠  modules.54.event.3.arguments.1.                               "Balance" --> "CurrencyId"
🛠  modules.54.event.5.name.                           "PayoutDeductionRateUpdated" --> "ClaimRewardDeductionRateUpdated"
🛠  modules.54.storage.entries.0.ty.Map.key.           "PoolId<T::RelaychainAccountId>" --> "PoolIdV0<T::RelaychainAccountId>"
🛠  modules.54.storage.entries.1.ty.Map.key.           "PoolId<T::RelaychainAccountId>" --> "PoolIdV0<T::RelaychainAccountId>"
🛠  modules.54.storage.entries.2.ty.Map.key.           "PoolId<T::RelaychainAccountId>" --> "PoolIdV0<T::RelaychainAccountId>"
🛠  modules.54.storage.entries.3.ty.DoubleMap.key1.    "PoolId<T::RelaychainAccountId>" --> "PoolIdV0<T::RelaychainAccountId>"
Changes:
- unmodified	= 72.92% (175)
- added		= 12.08% (29)
- modified	= 13.75% (33)
- removed	=  1.25% (3)
Skipped:
- documentation	=    13
- bytes		=     0
```

**Comment by xlc** [comment]
This updates some calls module-incentives.
They are governance only method and we don't have ongoing motion, so should be safe.
