### ISSUE TITLE
Release Checklist: 1.5.0

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1444]
## New Release Details:

- Scope: Client Only
- Network: Karura
- Client Version: 1.5.0
- Runtime Version: 1012
- Release Branch: [release-karura-1.5.0](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.5.0)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.4.3...release-karura-1.5.0
- Substrate version: [polkadot-v0.9.10](https://github.com/paritytech/substrate/tree/420db18eaa1a1f5ce9ba40dd6ccb69f7b3dd9bb7)
  - Diff: https://github.com/paritytech/substrate/compare/91061a7d925b5bc597804293da283477512ba4ff...420db18eaa1a1f5ce9ba40dd6ccb69f7b3dd9bb7
- ORML version: [37e42936c41dbdbaf0117c628c9eab0e06044844](https://github.com/open-web3-stack/open-runtime-module-library/tree/37e42936c41dbdbaf0117c628c9eab0e06044844)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/befa21562537b4a9a6de6a8d5985a10835d64df8...37e42936c41dbdbaf0117c628c9eab0e06044844
- Cumulus version: [polkadot-v0.9.10](https://github.com/paritytech/cumulus/tree/870b214693856e768ba482fe2d3b9a83b24e4540)
  - Diff: https://github.com/paritytech/cumulus/compare/fd80849dde5c209c20a996cfcc5aaacd4666dcbe...870b214693856e768ba482fe2d3b9a83b24e4540
- Polkadot version: [release-v0.9.10](https://github.com/paritytech/polkadot/tree/aeea9b7bd81919e014f7621f6c4b2eb9709d918f)
  - Diff: https://github.com/paritytech/polkadot/compare/7a9f624777ad2d2adb3a1e6797a31f9d653c9587...aeea9b7bd81919e014f7621f6c4b2eb9709d918f
- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.4.3
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1432

## Client Release

- [x] Verify client `Cargo.toml` version has been incremented since the last release.
  - Current version: 1.5.0
  - Last version: 1.4.3
- [x] Check the new client have run on the network without issue for at lease 12 hours.
- [x] Check new docker image has been published.
  - [acala/karura-node:1.5.0](https://hub.docker.com/layers/acala/karura-node/1.5.0/images/sha256-34e9aea419c1335b6579e19e2e1b3283b0244c081eb3a536db22e9e4e35bc286?context=explore)
- [x] Check new client is able to sync from scratch
  -  `docker run --rm acala/karura-node:latest --chain=karura -- --chain=dev`

## All Releases

- [x] Check new Github release is created with release logs.

## Post Release

- [x] Notify Discord announcement channel.
- [x] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)
