### ISSUE TITLE
Release Checklist: 1.4.4

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1476]
## New Release Details:

- Scope: Runtime Only
- Network: Karura
- Client Version: 1.4.4
- Runtime Version: 1013
- Release Branch: [release-karura-1.4.4](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.4.4)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.4.3...release-karura-1.4.4
- Substrate version: [polkadot-v0.9.9](https://github.com/paritytech/substrate/tree/91061a7d925b5bc597804293da283477512ba4ff)
  - Diff: Same as last release
- ORML version: [release-karura-1.4.4](https://github.com/open-web3-stack/open-runtime-module-library/tree/4368abf77b2f08f6fc7cc6612f19460d748e6f4d)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/befa21562537b4a9a6de6a8d5985a10835d64df8...4368abf77b2f08f6fc7cc6612f19460d748e6f4d
- Cumulus version: [polkadot-v0.9.9](https://github.com/paritytech/cumulus/tree/fd80849dde5c209c20a996cfcc5aaacd4666dcbe)
  - Diff: Same as last release
- Polkadot version: [release-v0.9.9](https://github.com/paritytech/polkadot/tree/7a9f624777ad2d2adb3a1e6797a31f9d653c9587)
  - Diff: Same as last release
- srtool details:

```
XXX
```

- subwasm info

```
XXX
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.4.3
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1432

## Runtime Release

- [ ] Verify `spec_version` has been incremented since the last release.
  - Current version: 1011
  - Last version: 1013
- [ ] Verify completed migrations are removed from any public networks.
- [ ] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [ ] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [ ] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [ ] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)
