### ISSUE TITLE
Release Checklist: 1.5.2

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1520]
## New Release Details:

- Scope: Runtime Only
- Network: Karura
- Client Version: 1.5.2
- Runtime Version: 1016
- Release Branch: [release-karura-1.5.2](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.5.2)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.5.1...release-karura-1.5.2
- Substrate version: [polkadot-v0.9.10](https://github.com/paritytech/substrate/tree/420db18eaa1a1f5ce9ba40dd6ccb69f7b3dd9bb7)
  - Diff: Same as last release
- ORML version: [release-karura-1.5.1](https://github.com/open-web3-stack/open-runtime-module-library/tree/72b0e5249efc3cfe4f521d2331b967716580f1c8)
  - Diff: Same as last release
- Cumulus version: [polkadot-v0.9.10](https://github.com/paritytech/cumulus/tree/870b214693856e768ba482fe2d3b9a83b24e4540)
  - Diff: Same as last release
- Polkadot version: [release-v0.9.10](https://github.com/paritytech/polkadot/tree/aeea9b7bd81919e014f7621f6c4b2eb9709d918f)
  - Diff: Same as last release
- srtool details:

```
Summary generated with srtool v0.9.16 using the docker image paritytech/srtool:1.53.0:
 Package     : karura-runtime v1.5.2
 GIT commit  : e5c61ebeb6cf31d2c174d5b4888890ef0819b965
 GIT tag     : 1.5.1
 GIT branch  : release-karura-1.5.2
 Rustc       : rustc 1.53.0 (53cb7b09b 2021-06-17)
 Time        : 2021-10-25T07:27:16Z

== Compact
 Version     : karura-1016 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 3.39 MB (3558362 bytes)
 Proposal    : 0x4e8b1fd27647223b68c4a61b4a0a114c919274cb47fc43059290deb04ccdcf0c
 IPFS        : QmPGXh9tD7NpToZcTt5TCj6R1UyeG65z8LG2W8bwEjbW8g
 BLAKE2_256  : 0xc937eda7a6830b1939c9ad2e5979d0caddd07658841e63d18b7b240ea3bd9bfd
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-1016 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 896.40 KB (917918 bytes)
 Compression : 74.21%
 Proposal    : 0xdd4603c92325e8775f26af01dc8cddf7005c6ad42c3a2f4fb1bb154a61db8a5e
 IPFS        : QmXDKp7PWPuK8rnbzS9dmdomRFDj9xi5A9htr8ZpAARyq4
 BLAKE2_256  : 0x6167683cb5f01867ee31bca4e7fe82dd96416afc43c2d18d4dcbe276ace1436a
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:		0.875 MB (917,918 bytes)
🗜  Compressed:			Yes, 74.20%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V13
🔥 Core version:		karura-1016 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0xdd4603c92325e8775f26af01dc8cddf7005c6ad42c3a2f4fb1bb154a61db8a5e
🗳️  authorizeUpgrade hash:	0x0f78c4a60be46cfee16162af6ab021d4f129916ac7afbbb866f42818cc79234c
#️⃣  Blake2-256 hash:		0x6167683cb5f01867ee31bca4e7fe82dd96416afc43c2d18d4dcbe276ace1436a
📦 IPFS:			https://www.ipfs.io/ipfs/QmXDKp7PWPuK8rnbzS9dmdomRFDj9xi5A9htr8ZpAARyq4
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.5.1
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1488

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 1015
  - Last version: 1014
- [x] Verify completed migrations are removed from any public networks.
- [x] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [ ] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [ ] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [ ] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)
