### ISSUE TITLE
Release Checklist: 1.5.3

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1527]
## New Release Details:

- Scope: Runtime Only
- Network: Karura
- Client Version: 1.5.3
- Runtime Version: 1017
- Release Branch: [release-karura-1.5.3](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.5.3)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.5.2...release-karura-1.5.3
- Substrate version: [polkadot-v0.9.10](https://github.com/paritytech/substrate/tree/420db18eaa1a1f5ce9ba40dd6ccb69f7b3dd9bb7)
  - Diff: Same as last release
- ORML version: [release-karura-1.5.1](https://github.com/open-web3-stack/open-runtime-module-library/tree/72b0e5249efc3cfe4f521d2331b967716580f1c8)
  - Diff: Same as last release
- Cumulus version: [polkadot-v0.9.10](https://github.com/paritytech/cumulus/tree/870b214693856e768ba482fe2d3b9a83b24e4540)
  - Diff: Same as last release
- Polkadot version: [release-v0.9.10](https://github.com/paritytech/polkadot/tree/aeea9b7bd81919e014f7621f6c4b2eb9709d918f)
  - Diff: Same as last release
- srtool details:

```
Summary generated with srtool v0.9.16 using the docker image paritytech/srtool:1.53.0:
 Package     : karura-runtime v1.5.3
 GIT commit  : 8288c94b9bc5532a2b5f7b9bf0ac3e01f22138a3
 GIT tag     : 1.5.2
 GIT branch  : release-karura-1.5.3
 Rustc       : rustc 1.53.0 (53cb7b09b 2021-06-17)
 Time        : 2021-10-26T21:40:19Z

== Compact
 Version     : karura-1018 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 3.39 MB (3557966 bytes)
 Proposal    : 0x4157a41d7b18eda8ecf7052f453cbcd529addd405462f82443b2a38cc4fa6e2e
 IPFS        : QmYtss1aVNfV4TjBfL8Va7U1axKbNpedRSehCryHidBpEe
 BLAKE2_256  : 0xff150dc504134a165942d8c0f47837a1e8106f187fb45d34c761f0a094620c48
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-1018 (karura-0.tx1.au1)
 Metadata    : V13
 Size        : 897.04 KB (918567 bytes)
 Compression : 74.19%
 Proposal    : 0x68aa73f774528c5ec65faf7461250dcaefa819ff244d0109ffdfb2980ef55276
 IPFS        : QmZ1oHavoZHsnAJP3AQ7ECjdjZyoWZZiHQDJMABfaFC3AY
 BLAKE2_256  : 0xcae21e1b0fb1c4ce170eabb342081ea4fa06d8aa3fdda4eefcc31905ca380f7d
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:		0.876 MB (918,567 bytes)
🗜  Compressed:			Yes, 74.18%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V13
🔥 Core version:		karura-1018 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0x68aa73f774528c5ec65faf7461250dcaefa819ff244d0109ffdfb2980ef55276
🗳️  authorizeUpgrade hash:	0x56ebfc157f6a6828bcf0371d745ec620a000fbed7e0a5927b8ce3a70fd25fa23
#️⃣  Blake2-256 hash:		0xcae21e1b0fb1c4ce170eabb342081ea4fa06d8aa3fdda4eefcc31905ca380f7d
📦 IPFS:			https://www.ipfs.io/ipfs/QmZ1oHavoZHsnAJP3AQ7ECjdjZyoWZZiHQDJMABfaFC3AY
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.5.2
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1520

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 1018
  - Last version: 1016
- [x] Verify completed migrations are removed from any public networks.
- [x] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [x] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [ ] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [ ] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)
