### ISSUE TITLE
Release Checklist: 1.6.0

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1543]
## New Release Details:

- Scope: Full Release
- Network: Karura
- Client Version: 1.6.0
- Runtime Version: 1019
- Release Branch: [release-karura-1.6.0](https://github.com/AcalaNetwork/Acala/tree/release-karura-1.6.0)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.5.3...release-karura-1.6.0
- Substrate version: [polkadot-v0.9.11](https://github.com/paritytech/substrate/tree/57346f6b24875f8935280dba51fa8ab0a9ba1e39)
  - Diff: https://github.com/paritytech/substrate/compare/420db18eaa1a1f5ce9ba40dd6ccb69f7b3dd9bb7...57346f6b24875f8935280dba51fa8ab0a9ba1e39
- ORML version: [release-karura-1.6.0](https://github.com/open-web3-stack/open-runtime-module-library/tree/38b53d39a59c230f4d80d8d8da60cd8c14073523)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/72b0e5249efc3cfe4f521d2331b967716580f1c8...38b53d39a59c230f4d80d8d8da60cd8c14073523
- Cumulus version: [polkadot-v0.9.11](https://github.com/paritytech/cumulus/tree/ede4d527c4fc5d84c43216b408a873625488574b)
  - Diff: https://github.com/paritytech/cumulus/compare/870b214693856e768ba482fe2d3b9a83b24e4540...ede4d527c4fc5d84c43216b408a873625488574b
- Polkadot version: [release-v0.9.11](https://github.com/paritytech/polkadot/tree/eb9f107e3a04687dcf80111563f2bcea7d5b15d3)
  - Diff: https://github.com/paritytech/polkadot/compare/aeea9b7bd81919e014f7621f6c4b2eb9709d918f...eb9f107e3a04687dcf80111563f2bcea7d5b15d3
- srtool details:

```
Summary generated with srtool v0.9.17 using the docker image paritytech/srtool:1.53.0:
 Package     : karura-runtime v1.6.0
 GIT commit  : 1c1776922355d2317fd14ae9f6ba31619a804b4c
 GIT tag     : 1.5.1
 GIT branch  : release-karura-1.6.0
 Rustc       : rustc 1.53.0 (53cb7b09b 2021-06-17)
 Time        : 2021-10-27T23:34:45Z

== Compact
 Version     : karura-1019 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 4.51 MB (4728412 bytes)
 Proposal    : 0xce03fa82c9970f042431bf2bc27b2af562e316d4d4a4743cc81ba51c7bf0e3ec
 IPFS        : QmaFY4a79L991RYFxUE58hqjs1DECMCi5eso5ZNKNPdU75
 BLAKE2_256  : 0x064501abb3af2f4314baeea31aeedb2c0aeab798441fed99a58b663643c8c5d2
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-1019 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 1.05 MB (1096369 bytes)
 Compression : 76.82%
 Proposal    : 0xe2898ba8f64f399b29b81ad7682aa3208487a509d74f7073a8644f14d149bb11
 IPFS        : QmQ7jd5v1ZnEWRxE1pP36ux3DVFtcrZnPg6LWzkg3nw1wP
 BLAKE2_256  : 0xce864af51bd0b781efb619d2d7f5c360dc72c15ea0be3646823c62166fe6fa9f
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:		1.046 MB (1,096,369 bytes)
🗜  Compressed:			Yes, 76.81%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V14
🔥 Core version:		karura-1019 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0xe2898ba8f64f399b29b81ad7682aa3208487a509d74f7073a8644f14d149bb11
🗳️  authorizeUpgrade hash:	0x5a83b67186e85d22b2aeeef7c9ca50baa6509696afd2b67b402fcf3855d2cc5c
#️⃣  Blake2-256 hash:		0xce864af51bd0b781efb619d2d7f5c360dc72c15ea0be3646823c62166fe6fa9f
📦 IPFS:			https://www.ipfs.io/ipfs/QmQ7jd5v1ZnEWRxE1pP36ux3DVFtcrZnPg6LWzkg3nw1wP
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.5.3
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1527

## Client Release

- [x] Verify client `Cargo.toml` version has been incremented since the last release.
  - Current version: 1.6.0
  - Last version: 1.5.1
- [ ] Check the new client have run on the network without issue for at lease 12 hours.
- [x] Check new docker image has been published.
  - [acala/karura-node:1.6.0](https://hub.docker.com/layers/acala/karura-node/1.6.0/images/sha256-65fdd250c6f3e0a8e05a854916bb7350066a2ea5f60656f5289aae1ebccc7300?context=explore)
- [x] Check new client is able to sync from scratch
  -  `docker run --rm acala/karura-node:latest --chain=karura -- --chain=dev`

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 1019
  - Last version: 1018
- [x] Verify completed migrations are removed from any public networks.
- [ ] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [ ] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [ ] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [ ] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)
