### ISSUE TITLE
Release Checklist: Karura 2.0.2

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1641]
## New Release Details:

- Scope: Full Release
- Network: Karura
- Client Version: 2.0.2
- Runtime Version: 2001
- Release Branch: [release-karura-1.6.0](https://github.com/AcalaNetwork/Acala/tree/release-karura-2.0.2)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-1.6.0...release-karura-2.0.2
- Substrate version: [polkadot-v0.9.12](https://github.com/paritytech/substrate/tree/d76f39995315ec36980908e4b99709bd14927044)
  - Diff: https://github.com/paritytech/substrate/compare/57346f6b24875f8935280dba51fa8ab0a9ba1e39...d76f39995315ec36980908e4b99709bd14927044
- ORML version: [polkadot-v0.9.12](https://github.com/open-web3-stack/open-runtime-module-library/tree/03fe5543968c3774738ab38c64323b1d1c7d58d4)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/38b53d39a59c230f4d80d8d8da60cd8c14073523...03fe5543968c3774738ab38c64323b1d1c7d58d4
- Cumulus version: [polkadot-v0.9.12](https://github.com/paritytech/cumulus/tree/c02514d8cb66d6860e597f75d53ca07119dbbf32)
  - Diff: https://github.com/paritytech/cumulus/compare/ede4d527c4fc5d84c43216b408a873625488574b...c02514d8cb66d6860e597f75d53ca07119dbbf32
- Polkadot version: [release-v0.9.12](https://github.com/paritytech/polkadot/tree/5feed981cf0fe671447eabaa9c0d235a8dd0003e)
  - Diff: https://github.com/paritytech/polkadot/compare/eb9f107e3a04687dcf80111563f2bcea7d5b15d3...5feed981cf0fe671447eabaa9c0d235a8dd0003e
- srtool details:

```
✨ Your Substrate WASM Runtime is ready! ✨
Summary generated with srtool v0.9.18 using the docker image paritytech/srtool:1.56.1:
 Package     : karura-runtime v2.0.2
 GIT commit  : 60b7da527176c610b5fbf14c048ceb8a2cc7aedf
 GIT tag     : mandala-runtime-2002
 GIT branch  : release-karura-2.0.2
 Rustc       : rustc 1.56.1 (59eed8a2a 2021-11-01)
 Time        : 2021-11-25T04:52:27Z

== Compact
 Version     : karura-2001 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 4.58 MB (4807272 bytes)
 Proposal    : 0xd04b9b3bbc08c070337c28ea13cb13a435215abb66ad14a9da5bc42db580411a
 IPFS        : QmbeV8iXbJknpWEvBjzeC8926DxQp9wt3SpVa19vDCfdNt
 BLAKE2_256  : 0x8df83c22646d6bc4e28326012f1b2b82ee4d497df6caafaf70788ab8ff146f06
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-2001 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 1.07 MB (1121127 bytes)
 Compression : 76.68%
 Proposal    : 0x4475cacb6e0612999c7287c715bad56e786ccb7bd905fb5a52884dec7b8d1f9a
 IPFS        : QmWVGq7w1t4ZeRbaowDFJ1bZRMyt9BsvYwsKcCU3agdJMQ
 BLAKE2_256  : 0x5ccf22068d3c24348197c80444ea105f9cc3f4e86859ae804fd5f76112911997
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:		1.069 MB (1,121,127 bytes)
🗜  Compressed:			Yes, 76.68%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V14
🔥 Core version:		karura-2001 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0x4475cacb6e0612999c7287c715bad56e786ccb7bd905fb5a52884dec7b8d1f9a
🗳️  authorizeUpgrade hash:	0xecab701f330c543ed191f3d9cdaf51a5a50e81b747888a171831c19fd9c7484d
#️⃣  Blake2-256 hash:		0x5ccf22068d3c24348197c80444ea105f9cc3f4e86859ae804fd5f76112911997
📦 IPFS:			https://www.ipfs.io/ipfs/QmWVGq7w1t4ZeRbaowDFJ1bZRMyt9BsvYwsKcCU3agdJMQ
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/1.6.0
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1543

## Client Release

- [x] Verify client `Cargo.toml` version has been incremented since the last release.
  - Current version: 2.0.2
  - Last version: 2.0.1
- [x] Check the new client have run on the network without issue for at lease 12 hours.
- [x] Check new docker image has been published.
  - [acala/karura-node:2.0.2](https://hub.docker.com/layers/acala/karura-node/2.0.2/images/sha256-20ff8362cdb22cb8e4d46c864a9dc6d402c2e83f28dcc76068e683018a72d95c?context=explore)
- [x] Check new client is able to sync from scratch
  -  `docker run --rm acala/karura-node:latest --chain=karura -- --chain=dev`

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 2001
  - Last version: 1019
- [x] Verify completed migrations are removed from any public networks.
- [x] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [x] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [x] Verify benchmarks & weights have been updated for any modified runtime logics.
- [x] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [x] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [x] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [x] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [x] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)

**Comment by xlc** [comment]
```
Metadata comparison:
Date: Fri Nov 26 10:28:12 UTC 2021
Reference: wss://karura-rpc-0.aca-api.network
Target version: acala 2.0.2-8765528-x86_64-linux-gnu
-------------------------------------------
              [Spec] name: karura
                     spec_version: 1019 -> 2001
                     transaction_version: 1
          [Metadata] version: 14
           [Modules] num: 62
                     [+] modules: AssetRegistry
                     [-] modules: EvmManager
                          [System] idx: 0 (calls: 10, storage: 17)
                       [Timestamp] idx: 1 (calls: 1, storage: 3)
                       [Scheduler] idx: 2 (calls: 6, storage: 4)
                        [Multisig] idx: 4 (calls: 4, storage: 3)
                           [Proxy] idx: 5 (calls: 10, storage: 3)
                [TransactionPause] idx: 6 (calls: 2, storage: 2)
                   [IdleScheduler] idx: 7 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                         [Vesting] idx: 13 (calls: 4, storage: 2)
              [TransactionPayment] idx: 14 (calls: 1, storage: 3)
                        [Treasury] idx: 20 (calls: 3, storage: 4)
                        [Bounties] idx: 21 (calls: 9, storage: 5)
                            [Tips] idx: 22 (calls: 6, storage: 3)
                 [ParachainSystem] idx: 30 (calls: 5 -> 4, storage: 20 -> 19)
                                   [-] calls: setUpgradeBlock
                             [setValidationData] idx: 1 -> 0 (args: 1)
                                                 (CumulusPrimitivesParachainInherentParachainInherentData)
                         [sudoSendUpwardMessage] idx: 2 -> 1 (args: 1)
                                                 (Bytes)
                              [authorizeUpgrade] idx: 3 -> 2 (args: 1)
                                                 (H256)
                        [enactAuthorizedUpgrade] idx: 4 -> 3 (args: 1)
                                                 (Bytes)
                                   [+] storage: upgradeRestrictionSignal
                                   [-] storage: pendingRelayChainBlockNumber, lastUpgrade
               [CollatorSelection] idx: 41 (calls: 7, storage: 7)
                         [Session] idx: 42 (calls: 2, storage: 8)
                  [SessionManager] idx: 45 (calls: 1, storage: 4)
                     [PolkadotXcm] idx: 51 (calls: 8 -> 10, storage: 10)
                                   [+] calls: limitedReserveTransferAssets, limitedTeleportAssets
                        [DmpQueue] idx: 53 (calls: 1, storage: 5)
                         [XTokens] idx: 54 (calls: 2, storage: 1)
                       [Authority] idx: 60 (calls: 8, storage: 3)
                  [GeneralCouncil] idx: 61 (calls: 6, storage: 7)
        [GeneralCouncilMembership] idx: 62 (calls: 7, storage: 3)
                [FinancialCouncil] idx: 63 (calls: 6, storage: 7)
      [FinancialCouncilMembership] idx: 64 (calls: 7, storage: 3)
                     [HomaCouncil] idx: 65 (calls: 6, storage: 7)
           [HomaCouncilMembership] idx: 66 (calls: 7, storage: 3)
              [TechnicalCommittee] idx: 67 (calls: 6, storage: 7)
    [TechnicalCommitteeMembership] idx: 68 (calls: 7, storage: 3)
                       [Democracy] idx: 69 (calls: 25, storage: 15)
                     [AcalaOracle] idx: 70 (calls: 1, storage: 5)
         [OperatorMembershipAcala] idx: 71 (calls: 7, storage: 3)
                         [Auction] idx: 80 (calls: 1, storage: 4)
                          [Prices] idx: 90 (calls: 2, storage: 2)
                             [Dex] idx: 91 (calls: 11, storage: 5)
                  [AuctionManager] idx: 100 (calls: 1, storage: 4)
                          [Honzon] idx: 102 (calls: 6, storage: 2)
                     [CdpTreasury] idx: 103 (calls: 3, storage: 3)
                       [CdpEngine] idx: 104 (calls: 4, storage: 5)
               [EmergencyShutdown] idx: 105 (calls: 3, storage: 3)
                        [HomaLite] idx: 115 (calls: 9 -> 11, storage: 7 -> 9)
                                   [+] calls: adjustAvailableStakingBalance, setStakingInterestRatePerUpdate
                                   [+] storage: stakingInterestRatePerUpdate, lastRedeemRequestKeyIterated
                      [Incentives] idx: 120 (calls: 6, storage: 5)
                             [EVM] idx: 130 (calls: 14, storage: 8)
                     [EvmAccounts] idx: 132 (calls: 2, storage: 3)
                            [Sudo] idx: 255 (calls: 4, storage: 2)
```
