### ISSUE TITLE
Release Checklist: 2.1.0

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1680]
## New Release Details:

- Scope: Full Release
- Network: Mandala & Karura
- Client Version: 2.1.0
- Runtime Version: 2010
- Release Branch: [release-karura-2.1.0](https://github.com/AcalaNetwork/Acala/tree/release-karura-2.1.0)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-2.0.2...release-karura-2.1.0
- Release Branch: [release-mandala-2.1.0](https://github.com/AcalaNetwork/Acala/tree/release-mandala-2.1.0)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-mandala-2.0.3...release-mandala-2.1.0
- Substrate version: [polkadot-v0.9.13](https://github.com/paritytech/substrate/tree/fcc54a72973d03afe7bf9e3ef2736050b3f33465)
  - Diff: https://github.com/paritytech/substrate/compare/d76f39995315ec36980908e4b99709bd14927044...fcc54a72973d03afe7bf9e3ef2736050b3f33465
- ORML version: [polkadot-v0.9.13](https://github.com/open-web3-stack/open-runtime-module-library/tree/1f520348f31b5e94b8a5dd7f8e6b8ec359df4177)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/03fe5543968c3774738ab38c64323b1d1c7d58d4...1f520348f31b5e94b8a5dd7f8e6b8ec359df4177
- Cumulus version: [polkadot-v0.9.13](https://github.com/paritytech/cumulus/tree/0be8e8fc214641e306e4f913dd64ff1913e46e95)
  - Diff: https://github.com/paritytech/cumulus/compare/c02514d8cb66d6860e597f75d53ca07119dbbf32...0be8e8fc214641e306e4f913dd64ff1913e46e95
- Polkadot version: [release-v0.9.13](https://github.com/paritytech/polkadot/tree/7d8f00b90cd6d87780123b3e08ca120cfb0c6e50)
  - Diff: https://github.com/paritytech/polkadot/compare/5feed981cf0fe671447eabaa9c0d235a8dd0003e...7d8f00b90cd6d87780123b3e08ca120cfb0c6e50
- srtool details:

```
Summary generated with srtool v0.9.18 using the docker image paritytech/srtool:1.56.1:
 Package     : karura-runtime v2.1.0
 GIT commit  : bda4d430cbecebf8720d700b976875d0d805ceca
 GIT tag     : 2.0.3
 GIT branch  : release-karura-2.1.0
 Rustc       : rustc 1.56.1 (59eed8a2a 2021-11-01)
 Time        : 2021-12-08T00:11:28Z

== Compact
 Version     : karura-2010 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 4.56 MB (4780280 bytes)
 Proposal    : 0x3a0c548c86111ea92b9c8f2a6e0208babee1e690811faf254002bd3647871905
 IPFS        : QmWsjGX8q2B7tabNcPzT6WANTczK1i6pZkqN3jGFQvCZnT
 BLAKE2_256  : 0x754a17271ef42e5f4ef555f78cf79e0ba7d797477aa7b81ed5b3aa196101ee52
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-2010 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 1.06 MB (1116085 bytes)
 Compression : 76.66%
 Proposal    : 0xd8cf7bdc549bea90eaac74628a9c410d622f31d1a2b35b56b05ef24d9a05c73f
 IPFS        : QmRjC8bK9zgVhEEwzrn1a79s7ook1nFoWbKo85R7m7EcAs
 BLAKE2_256  : 0x45bf4a2d38b7672b049d6ebfee8495dc4524405e42b0a2e12a32362ba9ed6354
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:		1.064 MB (1,116,085 bytes)
🗜  Compressed:			Yes, 76.65%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V14
🔥 Core version:		karura-2010 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0xd8cf7bdc549bea90eaac74628a9c410d622f31d1a2b35b56b05ef24d9a05c73f
🗳️  authorizeUpgrade hash:	0x4b5575f7259b006b39fd850f21f99a306469ba98ca720de77b89af04e9576157
#️⃣  Blake2-256 hash:		0x45bf4a2d38b7672b049d6ebfee8495dc4524405e42b0a2e12a32362ba9ed6354
📦 IPFS:			https://www.ipfs.io/ipfs/QmRjC8bK9zgVhEEwzrn1a79s7ook1nFoWbKo85R7m7EcAs
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/2.0.2
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1641

## Client Release

- [x] Verify client `Cargo.toml` version has been incremented since the last release.
  - Current version: 2.1.0
  - Last version: 2.0.3
- [ ] Check the new client have run on the network without issue for at lease 12 hours.
- [x] Check new docker image has been published.
  - [acala/karura-node:2.1.0](https://hub.docker.com/layers/acala/karura-node/2.1.0/images/sha256-23d8e7b2909831b72c9ae594a9be0cfaf17f1aa8e3a22ab8a18ac53e1b14df23?context=explore)
  - [acala/mandala-node:2.1.0](https://hub.docker.com/layers/acala/mandala-node/2.1.0/images/sha256-e3b09545227990448b7b7c52f638fc0a7c00c66931c5ff529b539829248f237b?context=explore)
- [ ] Check new client is able to sync from scratch
  -  `docker run --rm acala/karura-node:latest --chain=karura -- --chain=dev`

## Runtime Release

- [ ] Verify `spec_version` has been incremented since the last release.
  - Current version: 2010
  - Last version: 2001
- [x] Verify completed migrations are removed from any public networks.
- [x] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [x] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [x] Verify benchmarks & weights have been updated for any modified runtime logics.
- [x] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [x] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)

**Comment by xlc** [comment]
```
Metadata comparison:
Date: Wed Dec  8 03:06:16 UTC 2021
Reference: wss://karura-rpc-0.aca-api.network
Target version: acala 2.1.0-bda4d43-x86_64-linux-gnu
-------------------------------------------
              [Spec] name: karura
                     spec_version: 2001 -> 2010
                     transaction_version: 1
          [Metadata] version: 14
           [Modules] num: 62
                          [System] idx: 0 (calls: 10 -> 9, storage: 17)
                                   [-] calls: setChangesTrieConfig
                                    [setStorage] idx: 6 -> 5 (args: 1)
                                                 (Vec<(Bytes,Bytes)>)
                                   [killStorage] idx: 7 -> 6 (args: 1)
                                                 (Vec<Bytes>)
                                    [killPrefix] idx: 8 -> 7 (args: 2)
                                                 (Bytes, u32)
                               [remarkWithEvent] idx: 9 -> 8 (args: 1)
                                                 (Bytes)
                       [Timestamp] idx: 1 (calls: 1, storage: 3)
                       [Scheduler] idx: 2 (calls: 6, storage: 4)
                        [Multisig] idx: 4 (calls: 4, storage: 3)
                                       [asMulti] idx: 1 (args: 6)
                                                 (u16, Vec<AccountId32>, Option<PalletMultisigTimepoint>, Bytes, bool, u64) -> (u16, Vec<AccountId32>, Option<PalletMultisigTimepoint>, FrameSupportMiscWrapperKeepOpaque, bool, u64)
                                         [calls] value: (Bytes,AccountId32,u128) -> (FrameSupportMiscWrapperKeepOpaque,AccountId32,u128)
                           [Proxy] idx: 5 (calls: 10, storage: 3)
                [TransactionPause] idx: 6 (calls: 2, storage: 2)
                   [IdleScheduler] idx: 7 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                         [Vesting] idx: 13 (calls: 4, storage: 2)
              [TransactionPayment] idx: 14 (calls: 1, storage: 3)
                        [Treasury] idx: 20 (calls: 3, storage: 4)
                        [Bounties] idx: 21 (calls: 9, storage: 5)
                            [Tips] idx: 22 (calls: 6, storage: 3)
                 [ParachainSystem] idx: 30 (calls: 4, storage: 19)
               [CollatorSelection] idx: 41 (calls: 7, storage: 7)
                         [Session] idx: 42 (calls: 2, storage: 8)
                  [SessionManager] idx: 45 (calls: 1, storage: 4)
                     [PolkadotXcm] idx: 51 (calls: 10, storage: 10)
                        [DmpQueue] idx: 53 (calls: 1, storage: 5)
                         [XTokens] idx: 54 (calls: 2 -> 4, storage: 1)
                                   [+] calls: transferWithFee, transferMultiassetWithFee
                       [Authority] idx: 60 (calls: 8, storage: 3)
                  [GeneralCouncil] idx: 61 (calls: 6, storage: 7)
        [GeneralCouncilMembership] idx: 62 (calls: 7, storage: 3)
                [FinancialCouncil] idx: 63 (calls: 6, storage: 7)
      [FinancialCouncilMembership] idx: 64 (calls: 7, storage: 3)
                     [HomaCouncil] idx: 65 (calls: 6, storage: 7)
           [HomaCouncilMembership] idx: 66 (calls: 7, storage: 3)
              [TechnicalCommittee] idx: 67 (calls: 6, storage: 7)
    [TechnicalCommitteeMembership] idx: 68 (calls: 7, storage: 3)
                       [Democracy] idx: 69 (calls: 25, storage: 15)
                     [AcalaOracle] idx: 70 (calls: 1, storage: 5)
         [OperatorMembershipAcala] idx: 71 (calls: 7, storage: 3)
                         [Auction] idx: 80 (calls: 1, storage: 4)
                          [Prices] idx: 90 (calls: 2, storage: 2)
                             [Dex] idx: 91 (calls: 11, storage: 5)
                  [AuctionManager] idx: 100 (calls: 1, storage: 4)
                          [Honzon] idx: 102 (calls: 6, storage: 2)
                     [CdpTreasury] idx: 103 (calls: 3, storage: 3)
                       [CdpEngine] idx: 104 (calls: 4, storage: 5)
               [EmergencyShutdown] idx: 105 (calls: 3, storage: 3)
                        [HomaLite] idx: 115 (calls: 11, storage: 9)
                      [Incentives] idx: 120 (calls: 6, storage: 5)
                   [AssetRegistry] idx: 122 (calls: 2, storage: 6)
                             [EVM] idx: 130 (calls: 14, storage: 8)
                     [EvmAccounts] idx: 132 (calls: 2, storage: 3)
                            [Sudo] idx: 255 (calls: 4, storage: 2)
```
