### ISSUE TITLE
Release Checklist: 2.1.1

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1715]
## New Release Details:

- Scope: Full
- Network: Mandala | Karura | Acala
- Client Version: 2.1.1
- Runtime Version: 2011
- Mandala Release Branch: [release-mandala-2.1.1](https://github.com/AcalaNetwork/Acala/tree/release-mandala-2.1.1)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-mandala-2.1.0...release-mandala-2.1.1
- Karura Release Branch: [release-karura-2.1.1](https://github.com/AcalaNetwork/Acala/tree/release-karura-2.1.1)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-2.1.0...release-karura-2.1.1
- Acala Release Branch: [release-acala-2.1.1](https://github.com/AcalaNetwork/Acala/tree/release-acala-2.1.1)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-acala-2.0.3...release-acala-2.1.1
- Substrate version: [polkadot-v0.9.13](https://github.com/paritytech/substrate/tree/fcc54a72973d03afe7bf9e3ef2736050b3f33465)
  - Diff: Same as last release
- ORML version: [1c80da43a720d1b957e1ba12238e4d98b2ee8cf9](https://github.com/open-web3-stack/open-runtime-module-library/tree/1c80da43a720d1b957e1ba12238e4d98b2ee8cf9)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/1f520348f31b5e94b8a5dd7f8e6b8ec359df4177...1c80da43a720d1b957e1ba12238e4d98b2ee8cf9
- Cumulus version: [v0.9.13](https://github.com/paritytech/cumulus/tree/0be8e8fc214641e306e4f913dd64ff1913e46e95)
  - Diff: Same as last release
- Polkadot version: [v0.9.13](https://github.com/paritytech/polkadot/tree/7d8f00b90cd6d87780123b3e08ca120cfb0c6e50)
  - Diff: Same as last release
- srtool details:

Acala

```
Summary generated with srtool v0.9.18 using the docker image paritytech/srtool:1.56.1:
 Package     : acala-runtime v2.1.1
 GIT commit  : 8beb6f8659ca90def7e5c3949bf5414d8bc8befe
 GIT tag     : 2.1.0
 GIT branch  : master
 Rustc       : rustc 1.56.1 (59eed8a2a 2021-11-01)
 Time        : 2021-12-20T04:17:46Z

== Compact
 Version     : acala-2011 (acala-0.tx1.au1)
 Metadata    : V14
 Size        : 4.74 MB (4970991 bytes)
 Proposal    : 0x9824c938e36b2a4e13c2d1a9f0136caae59c95e723b71bc9d315b5b25e35a624
 IPFS        : Qmc3BNGR4uvdw61E1pHbDva5pwj4bTK88Miw8K78DqFUik
 BLAKE2_256  : 0xb0ac1d769a1c6d1b6495c4adea04fb170feaa9269fc689ba6df91ecfc278999e
 Wasm        : runtime/acala/target/srtool/release/wbuild/acala-runtime/acala_runtime.compact.wasm

== Compressed
 Version     : acala-2011 (acala-0.tx1.au1)
 Metadata    : V14
 Size        : 1.11 MB (1161249 bytes)
 Compression : 76.64%
 Proposal    : 0x090c6094c9cc3c9edd1d59743cd629de8fbe619d7f9c9ef6f6d45e7bf5e7f7d6
 IPFS        : QmYwNxcMvkRro2gESP4sWn9YtJkTesGRY9iFi6kXj3xCTK
 BLAKE2_256  : 0x8a3e5a9b3d356aeb46d9e9dfe6809677cf60a554a53b32c7a28bbca3d847477d
 Wasm        : runtime/acala/target/srtool/release/wbuild/acala-runtime/acala_runtime.compact.compressed.wasm
```

Karura

```
Summary generated with srtool v0.9.18 using the docker image paritytech/srtool:1.56.1:
 Package     : karura-runtime v2.1.1
 GIT commit  : 8beb6f8659ca90def7e5c3949bf5414d8bc8befe
 GIT tag     : 2.1.0
 GIT branch  : master
 Rustc       : rustc 1.56.1 (59eed8a2a 2021-11-01)
 Time        : 2021-12-20T04:08:01Z

== Compact
 Version     : karura-2011 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 4.63 MB (4858160 bytes)
 Proposal    : 0xec325bb408615d5b988e222693105ad2076ea8615ea7edad1c56421a42605b65
 IPFS        : QmZhE6USGtLDaivRfQ6ZN2xeEawr5aAfaRRXF88cCh8s5z
 BLAKE2_256  : 0x7ed01d98a58b7326e7185723eb70a618901c1995a1a43604e87121f4226293ef
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-2011 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 1.09 MB (1147596 bytes)
 Compression : 76.38%
 Proposal    : 0xba81df361e4dbfdba6e4f17f76079fd9b3a5dff9dd19226cd0e1541bb4b944d9
 IPFS        : QmVoqeeLbhSiRdN3ide1oFyBE2KA65XoLiaqH9aCG2hfZ4
 BLAKE2_256  : 0x529246d6beb4c158445d7fb5bfb9f20a001999f70c027315982f9ee8266a321d
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

Acala

```
🏋️  Runtime size:		1.107 MB (1,161,249 bytes)
🗜  Compressed:			Yes, 76.64%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V14
🔥 Core version:		acala-2011 (acala-0.tx1.au1)
🗳️  system.setCode hash:		0x090c6094c9cc3c9edd1d59743cd629de8fbe619d7f9c9ef6f6d45e7bf5e7f7d6
🗳️  authorizeUpgrade hash:	0x98c0f804a16effca30a83c3878a05344bc5e91cbec7df903ab85bc735dc04a5e
#️⃣  Blake2-256 hash:		0x8a3e5a9b3d356aeb46d9e9dfe6809677cf60a554a53b32c7a28bbca3d847477d
📦 IPFS:			https://www.ipfs.io/ipfs/QmYwNxcMvkRro2gESP4sWn9YtJkTesGRY9iFi6kXj3xCTK
```

Karura

```
🏋️  Runtime size:		1.094 MB (1,147,596 bytes)
🗜  Compressed:			Yes, 76.38%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V14
🔥 Core version:		karura-2011 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0xba81df361e4dbfdba6e4f17f76079fd9b3a5dff9dd19226cd0e1541bb4b944d9
🗳️  authorizeUpgrade hash:	0xca74dad4a3e323f36a33a04d7d8c756695e823dc4bbdd2744dddda424392bd83
#️⃣  Blake2-256 hash:		0x529246d6beb4c158445d7fb5bfb9f20a001999f70c027315982f9ee8266a321d
📦 IPFS:			https://www.ipfs.io/ipfs/QmVoqeeLbhSiRdN3ide1oFyBE2KA65XoLiaqH9aCG2hfZ4
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/2.1.0
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1680

## Client Release

- [x] Verify client `Cargo.toml` version has been incremented since the last release.
  - Current version: 2.1.1
  - Last version: 2.1.0
- [x] Check the new client have run on the network without issue for at lease 12 hours.
- [x] Check new docker image has been published.
  - [acala/karura-node:2.1.1](https://hub.docker.com/layers/acala/karura-node/2.1.1/images/sha256-568d6d84157ca0a5366cd824b98aab58e758a3b76fdd303e00f9d7e6e2da6777?context=explore)
  - [acala/acala-node:2.1.1](https://hub.docker.com/layers/acala/acala-node/2.1.1/images/sha256-7930167cdbff6b6b63d3192e7b14207be2011184287d2157b1c12e95caec6c21?context=explore)
- [x] Check new client is able to sync from scratch
  -  `docker run --rm acala/karura-node:latest --chain=karura -- --chain=dev`

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 2011
  - Last version: 2010
- [x] Verify completed migrations are removed from any public networks.
- [ ] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [x] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [x] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [x] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [x] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)

**Comment by xlc** [comment]
```
Metadata comparison:
Date: Mon Dec 20 21:23:58 UTC 2021
Reference: wss://karura-rpc-0.aca-api.network
Target version: acala 2.1.1-8beb6f8-x86_64-linux-gnu
-------------------------------------------
              [Spec] name: karura
                     spec_version: 2010 -> 2011
                     transaction_version: 1
          [Metadata] version: 14
           [Modules] num: 62
                          [System] idx: 0 (calls: 9, storage: 17)
                       [Timestamp] idx: 1 (calls: 1, storage: 3)
                       [Scheduler] idx: 2 (calls: 6, storage: 4)
                        [Multisig] idx: 4 (calls: 4, storage: 3)
                           [Proxy] idx: 5 (calls: 10, storage: 3)
                [TransactionPause] idx: 6 (calls: 2, storage: 2)
                   [IdleScheduler] idx: 7 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                         [Vesting] idx: 13 (calls: 4, storage: 2)
              [TransactionPayment] idx: 14 (calls: 1, storage: 3)
                        [Treasury] idx: 20 (calls: 3, storage: 4)
                        [Bounties] idx: 21 (calls: 9, storage: 5)
                            [Tips] idx: 22 (calls: 6, storage: 3)
                 [ParachainSystem] idx: 30 (calls: 4, storage: 19)
               [CollatorSelection] idx: 41 (calls: 7, storage: 7)
                         [Session] idx: 42 (calls: 2, storage: 8)
                  [SessionManager] idx: 45 (calls: 1, storage: 4)
                     [PolkadotXcm] idx: 51 (calls: 10, storage: 10)
                        [DmpQueue] idx: 53 (calls: 1, storage: 5)
                         [XTokens] idx: 54 (calls: 4, storage: 1)
                       [Authority] idx: 60 (calls: 8, storage: 3)
                  [GeneralCouncil] idx: 61 (calls: 6, storage: 7)
        [GeneralCouncilMembership] idx: 62 (calls: 7, storage: 3)
                [FinancialCouncil] idx: 63 (calls: 6, storage: 7)
      [FinancialCouncilMembership] idx: 64 (calls: 7, storage: 3)
                     [HomaCouncil] idx: 65 (calls: 6, storage: 7)
           [HomaCouncilMembership] idx: 66 (calls: 7, storage: 3)
              [TechnicalCommittee] idx: 67 (calls: 6, storage: 7)
    [TechnicalCommitteeMembership] idx: 68 (calls: 7, storage: 3)
                       [Democracy] idx: 69 (calls: 25, storage: 15)
                     [AcalaOracle] idx: 70 (calls: 1, storage: 5)
         [OperatorMembershipAcala] idx: 71 (calls: 7, storage: 3)
                         [Auction] idx: 80 (calls: 1, storage: 4)
                          [Prices] idx: 90 (calls: 2, storage: 2)
                             [Dex] idx: 91 (calls: 11, storage: 5)
                  [AuctionManager] idx: 100 (calls: 1, storage: 4)
                          [Honzon] idx: 102 (calls: 6, storage: 2)
                        [closeLoanHasDebitByDex] idx: 1 (args: 3 -> 2)
                                                 (AcalaPrimitivesCurrencyCurrencyId, Compact<u128>, Option<Vec<AcalaPrimitivesCurrencyCurrencyId>>) -> (AcalaPrimitivesCurrencyCurrencyId, Compact<u128>)
                     [CdpTreasury] idx: 103 (calls: 3, storage: 3)
                       [CdpEngine] idx: 104 (calls: 4, storage: 5)
               [EmergencyShutdown] idx: 105 (calls: 3, storage: 3)
                        [HomaLite] idx: 115 (calls: 11, storage: 9)
                      [Incentives] idx: 120 (calls: 6, storage: 5)
                   [AssetRegistry] idx: 122 (calls: 2, storage: 6)
                             [EVM] idx: 130 (calls: 14, storage: 8)
                                   [+] calls: createNftContract
                                   [-] calls: createNetworkContract
                     [EvmAccounts] idx: 132 (calls: 2, storage: 3)
                            [Sudo] idx: 255 (calls: 4, storage: 2)
```

**Comment by xlc** [comment]
Acala runtime 2012

```
Summary generated with srtool v0.9.18 using the docker image paritytech/srtool:1.56.1:
 Package     : acala-runtime v2.1.1
 GIT commit  : cf4038c0535f49e45fa9b38bf266489bda9ffceb
 GIT tag     : 2.1.1
 GIT branch  : master
 Rustc       : rustc 1.56.1 (59eed8a2a 2021-11-01)
 Time        : 2021-12-22T04:01:17Z

== Compact
 Version     : acala-2012 (acala-0.tx1.au1)
 Metadata    : V14
 Size        : 4.74 MB (4970991 bytes)
 Proposal    : 0x36dcb79a7624ddd0b3772ada00d862e11ca8bda37f271f42f3dc3c91ea526249
 IPFS        : QmVicremYdmcYRQFW5TqKxrf8nQUmDQpr3DqnMFmeW9Ah9
 BLAKE2_256  : 0x305d42989b6a2a5978de099cc31e2008d84e5b5985e8e98a6ac821b5519fae8b
 Wasm        : runtime/acala/target/srtool/release/wbuild/acala-runtime/acala_runtime.compact.wasm

== Compressed
 Version     : acala-2012 (acala-0.tx1.au1)
 Metadata    : V14
 Size        : 1.11 MB (1161296 bytes)
 Compression : 76.64%
 Proposal    : 0x6c8f101201dce426b362be8fe2974a1e0cab7b8d33aad2598d2d6c5468716593
 IPFS        : QmWF3qJWphTR5GQF7XKUnUnfWDCUMGhrRrsvtVQBMdpdpD
 BLAKE2_256  : 0x042ed6d53a0c225e722e4904aa61a75dedfb81efbb71b7691a37a17296d33edd
 Wasm        : runtime/acala/target/srtool/release/wbuild/acala-runtime/acala_runtime.compact.compressed.wasm
```
