### ISSUE TITLE
Release Checklist: 2.1.2

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1745]
## New Release Details:

- Scope: Runtime Only
- Network: Karura
- Client Version: 2.1.2
- Runtime Version: 2012
- Release Branch: [release-karura-2.1.2](https://github.com/AcalaNetwork/Acala/tree/release-karura-2.1.2)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-2.1.1...release-karura-2.1.2
- Substrate version: [polkadot-v0.9.13](https://github.com/paritytech/substrate/tree/fcc54a72973d03afe7bf9e3ef2736050b3f33465)
  - Diff: Same as last release
- ORML version: [8d076372849a4dced5468f0f14db96b7145160ee](https://github.com/open-web3-stack/open-runtime-module-library/tree/8d076372849a4dced5468f0f14db96b7145160ee)
  - Diff: https://github.com/open-web3-stack/open-runtime-module-library/compare/1c80da43a720d1b957e1ba12238e4d98b2ee8cf9...8d076372849a4dced5468f0f14db96b7145160ee
- Cumulus version: [v0.9.13](https://github.com/paritytech/cumulus/tree/0be8e8fc214641e306e4f913dd64ff1913e46e95)
  - Diff: Same as last release
- Polkadot version: [v0.9.13](https://github.com/paritytech/polkadot/tree/7d8f00b90cd6d87780123b3e08ca120cfb0c6e50)
  - Diff: Same as last release
- srtool details:

```
Summary generated with srtool v0.9.18 using the docker image paritytech/srtool:1.56.1:
 Package     : karura-runtime v2.1.2
 GIT commit  : ee85061464b9ff35581415b6a5ba785d55bc3ff1
 GIT tag     : 2.1.1
 GIT branch  : release-karura-2.1.2
 Rustc       : rustc 1.56.1 (59eed8a2a 2021-11-01)
 Time        : 2022-01-03T09:12:24Z

== Compact
 Version     : karura-2012 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 4.81 MB (5041618 bytes)
 Proposal    : 0xc227ca1f5154fae742eb98cfcb0d9b3873d7a36bad9c423e7b2fc3ddcc3e4fd9
 IPFS        : QmdHswcn8djKYs4RuYbMdNBz8xrAtyhmxVK5SSNfyNJiJJ
 BLAKE2_256  : 0xb17cd8f8b6db477d31e869bf367b7e592f495cb84e43e41897207f047ff063bb
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-2012 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 1.13 MB (1188017 bytes)
 Compression : 76.44%
 Proposal    : 0xb5bffceb748ca86d215b8a53217fbe8133d103c8fc22046d21e4dd13265d3931
 IPFS        : QmSqfSvSRN5QVeeqjTvS8cKma33qa6jn1G3mFG4fkc196H
 BLAKE2_256  : 0x8bb582464830a502575c6f79f1465653e0128e0d3fdd3425d571e10c5ca3b4c8
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:		1.133 MB (1,188,017 bytes)
🗜  Compressed:			Yes, 76.44%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V14
🔥 Core version:		karura-2012 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0xb5bffceb748ca86d215b8a53217fbe8133d103c8fc22046d21e4dd13265d3931
🗳️  authorizeUpgrade hash:	0xf2f5507889345bb29afa3c2b17d90ce173f55b15e2216caca9be6618e0419430
#️⃣  Blake2-256 hash:		0x8bb582464830a502575c6f79f1465653e0128e0d3fdd3425d571e10c5ca3b4c8
📦 IPFS:			https://www.ipfs.io/ipfs/QmSqfSvSRN5QVeeqjTvS8cKma33qa6jn1G3mFG4fkc196H
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/2.1.2
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1715

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 2011
  - Last version: 2012
- [x] Verify completed migrations are removed from any public networks.
- [ ] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [ ] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [ ] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [x] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [ ] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)
