### ISSUE TITLE
Release Checklist: 2.1.3

### ISSUE THREAD

**Issue by StrawberryFlavor** [AcalaNetwork/Acala#1750]
## New Release Details:

- Scope: Runtime Only
- Network: Karura
- Client Version: 2.1.3
- Runtime Version: 2013
- Release Branch: [release-karura-2.1.3](https://github.com/AcalaNetwork/Acala/tree/release-karura-2.1.3)
  -  Diff: https://github.com/AcalaNetwork/Acala/compare/release-karura-2.1.2...release-karura-2.1.3
- Substrate version: [polkadot-v0.9.13](https://github.com/paritytech/substrate/tree/fcc54a72973d03afe7bf9e3ef2736050b3f33465)
  - Diff: Same as last release
- ORML version: [8d076372849a4dced5468f0f14db96b7145160ee](https://github.com/open-web3-stack/open-runtime-module-library/tree/8d076372849a4dced5468f0f14db96b7145160ee)
  - Diff: Same as last release
- Cumulus version: [v0.9.13](https://github.com/paritytech/cumulus/tree/0be8e8fc214641e306e4f913dd64ff1913e46e95)
  - Diff: Same as last release
- Polkadot version: [v0.9.13](https://github.com/paritytech/polkadot/tree/7d8f00b90cd6d87780123b3e08ca120cfb0c6e50)
  - Diff: Same as last release
- srtool details:

```
Summary generated with srtool v0.9.18 using the docker image paritytech/srtool:1.56.1:
 Package     : karura-runtime v2.1.3
 GIT commit  : ac1f4049f463fbc3365032f6ae14c90255db148a
 GIT tag     : 2.1.2
 GIT branch  : release-karura-2.1.3
 Rustc       : rustc 1.56.1 (59eed8a2a 2021-11-01)
 Time        : 2022-01-05T03:52:48Z

== Compact
 Version     : karura-2013 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 4.80 MB (5037002 bytes)
 Proposal    : 0xb29191192f3137eba178ba0c694912f792925b2e604297389f6dae993716bab5
 IPFS        : QmSQQGhVy64Rzz2Y9yiuogMxJoE5tp7cugUoL7uxx1tqV8
 BLAKE2_256  : 0x18a4a5de78217a2d8b51b4d0e9e212b7c1ada4fbfc00d50db9930b67b2c68ee9
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.wasm

== Compressed
 Version     : karura-2013 (karura-0.tx1.au1)
 Metadata    : V14
 Size        : 1.12 MB (1171389 bytes)
 Compression : 76.75%
 Proposal    : 0x25bb7d33ca0473b490555f8b6b2cbca0d354f588890ea37dca5b57c8c0becad3
 IPFS        : QmeeY6bgmiDwMTjNwxM6hebWjQ37Ae9DooeqcVjsprDPx3
 BLAKE2_256  : 0xeddd2fcbd42060351cad564e99d653828482519a42299b8652aee93c7b620fd5
 Wasm        : runtime/karura/target/srtool/release/wbuild/karura-runtime/karura_runtime.compact.compressed.wasm
```

- subwasm info

```
🏋️  Runtime size:		1.117 MB (1,171,389 bytes)
🗜  Compressed:			Yes, 76.74%
✨ Reserved meta:		OK - [6D, 65, 74, 61]
🎁 Metadata version:		V14
🔥 Core version:		karura-2013 (karura-0.tx1.au1)
🗳️  system.setCode hash:		0x25bb7d33ca0473b490555f8b6b2cbca0d354f588890ea37dca5b57c8c0becad3
🗳️  authorizeUpgrade hash:	0xe1dd5107d16209de598e0cad4f05004705b8031a426ad164479972634e00f685
#️⃣  Blake2-256 hash:		0xeddd2fcbd42060351cad564e99d653828482519a42299b8652aee93c7b620fd5
📦 IPFS:			https://www.ipfs.io/ipfs/QmeeY6bgmiDwMTjNwxM6hebWjQ37Ae9DooeqcVjsprDPx3
```

- Previous Release: https://github.com/AcalaNetwork/Acala/releases/tag/2.1.3
  - Checklist: https://github.com/AcalaNetwork/Acala/issues/1745

## Runtime Release

- [x] Verify `spec_version` has been incremented since the last release.
  - Current version: 2011
  - Last version: 2012
- [x] Verify completed migrations are removed from any public networks.
- [ ] Review subwasm diff
  - `subwasm diff wss://karura-rpc-2.aca-api.network/ws karura_runtime.compact.compressed.wasm`
- [ ] Verify extrinsic ordering has stayed the same. Bump `transaction_version` if not.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new extrinsics have been correctly whitelisted/blacklisted for proxy filters.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics.
- [ ] Verify we included all the necessary migrations.
  - [ ] ORML
  - [ ] Substrate
  - [ ] Cumulus
  - [ ] Polkadot
  - [ ] Acala
- [ ] Verify new migrations complete successfully and the runtime state is correctly updated for any public networks.
  - [ ] Verify the execution time to perform runtime upgrade with Karura/Acala onchain data.
- [x] Ensure WASM is reproducible
  - `make srtool-build-wasm-karura`

## All Releases

- [x] Check new Github release is created with release logs.

## Post Release

- [ ] Notify Discord announcement channel.
- [ ] Ensure our own nodes are updated

### SDK & Tools

- [ ] acala.js
- [ ] txwrapper
- [ ] sidecar
- [ ] acala-subql
- [ ] oracle dispatcher

### dApps & Wallets

- [ ] polkadot apps
- [ ] Acala dApp
- [ ] Polkawallet

### Other

- [ ] Exchanges
- [ ] Gauntlet
- [ ] Faucet (for Mandala)
