### ISSUE TITLE
EVM release checklist

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#1801]
Before we enable EVM on Karura, we need to make sure:

- [x] We include the standard set of precompiles and they are up to date
- [x] The scheduler precompile should be disabled for Karura
- [x] Make sure all custom precompiles are safe
- [x] Double check gas to weight ratio
- [x] Double check storage byte fee
- [x] https://github.com/AcalaNetwork/Acala/issues/1846
- [x] Audit EVM config & precompiles
- [x] Double check evm call transaction fee is reasonable 
- [x] Audit predeploy contracts
- [x] https://github.com/AcalaNetwork/Acala/issues/1427
- [x] Enable EVM calls
- [x] https://github.com/AcalaNetwork/Acala/issues/2027
- [x] Ensure wormhole contracts are successfully deployed
- [ ] https://github.com/AcalaNetwork/Acala/issues/1967
- [ ] https://github.com/AcalaNetwork/Acala/issues/2085

**Comment by zjb0807** [comment]
Deploy Token pre-deploy contract will use 199,930,910,452(39.98%) weight.

**Comment by gluneau** [comment]
Is placing the token contract for each precompiled tokens a step in this process?

**Comment by zjb0807** [comment]
#2166

**Comment by zjb0807** [comment]
honzon-bridge system account: `qmmNufxeWaAUy6KGcxwC3u3EagHc9G9mbhHuxEaefbfXg3V`
