### ISSUE TITLE
Karura Launch checklist

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#931]
- [x] upgrade Substrate & Cumulus
- [x] update Karura parameters #876 
- [x] update Sudo key
- [x] update ParaId
- [x] update genesis token distribution & vesting
  - [x] #881 
  - [x] #106
- [x] implement aura + staking for collator 
  - [x] start with something similar to statement #873 
- [x] CI to build Karura docker image
  - [x] #880 
  - [x] srtool integration
- [x] make sure the code is ready
  - [x] able to produce block
  - [x] able to use try-runtime to verify new runtime
  - [x] able to runtime upgrade
  - [x] able to sudo transfer / vested transfer
- [x] bump versions & chain spec
- [x] check genesis key works
- [x] final check with deps of validators

**Comment by shaunxw** [comment]
I think we need to re-do all the benchmarks for Karura before launch?
