### ISSUE TITLE
Post Karura Launch checklist

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#988]
- [ ] implement staking & nominate & rewards #921 
- [ ] distribute crowdloan & other rewards
- [ ] make sure we can use tryrun to check new runtime before upgrade it
- [ ] review benchmarks
- [ ] update collator candidacy_bond
- [ ] fix benchmark tests (broken due to ED change & oracle provider count requirement)
  - revert https://github.com/AcalaNetwork/Acala/pull/1006/commits/11a84d914d8a44fdc3a8b374b21b08c8c6a148df
